import Exercise from '../models/Exercise';

type ExerciseCategory = 'upper_body' | 'lower_body' | 'cardio' | 'flexibility' | 'balance' | 'breathing' | 'core';
type ExerciseDifficulty = 'beginner' | 'intermediate' | 'advanced';

interface ExerciseSeedData {
  name: string;
  description: string;
  category: ExerciseCategory;
  difficulty: ExerciseDifficulty;
  equipmentNeeded: string;
  minPostOpWeek: number;
  maxPostOpWeek: number | null;
  contraindications?: string;
  instructions: string;
  recoveryBenefit: string;
  defaultSets: number;
  defaultReps: number;
  defaultDuration: number;
  isActive: boolean;
}

const exercises: ExerciseSeedData[] = [
  // ========== PHASE 1: WEEKS 1-2 - IMMEDIATE POST-OP (Very Gentle, Bed/Chair Exercises) ==========

  // BREATHING EXERCISES - Critical for lung function
  {
    name: 'Deep Breathing Exercise',
    description: 'Slow, controlled deep breaths to expand lungs and prevent complications',
    category: 'breathing',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    contraindications: 'Severe chest pain, dizziness, shortness of breath at rest',
    instructions: '1. Sit upright with back supported\n2. Inhale slowly through nose for 4 counts\n3. Hold breath for 2 counts\n4. Exhale slowly through mouth for 6 counts\n5. Rest and repeat',
    recoveryBenefit: 'Prevents pneumonia and lung complications, improves oxygen delivery to healing heart tissue, reduces risk of blood clots',
    defaultSets: 4,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Incentive Spirometer',
    description: 'Device-assisted breathing to prevent lung complications',
    category: 'breathing',
    difficulty: 'beginner',
    equipmentNeeded: 'Incentive spirometer',
    minPostOpWeek: 1,
    maxPostOpWeek: 6,
    instructions: '1. Sit upright\n2. Exhale normally\n3. Seal lips around mouthpiece\n4. Inhale slowly and deeply\n5. Hold at target level for 3-5 seconds\n6. Exhale slowly and rest',
    recoveryBenefit: 'Expands lung capacity, prevents atelectasis (lung collapse), improves blood oxygenation critical for healing',
    defaultSets: 1,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Diaphragmatic Breathing',
    description: 'Belly breathing to strengthen diaphragm and reduce chest strain',
    category: 'breathing',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Lie on back or sit comfortably\n2. Place one hand on chest, one on belly\n3. Inhale through nose - belly rises, chest stays still\n4. Exhale through pursed lips - belly falls\n5. Focus on belly movement only',
    recoveryBenefit: 'Strengthens primary breathing muscle, reduces work on healing chest muscles, improves breathing efficiency and oxygen intake',
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Pursed Lip Breathing',
    description: 'Controlled exhalation technique to improve lung emptying',
    category: 'breathing',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Relax neck and shoulders\n2. Inhale through nose for 2 counts\n3. Purse lips as if whistling\n4. Exhale slowly through pursed lips for 4 counts\n5. Keep exhalation twice as long as inhalation',
    recoveryBenefit: 'Improves ventilation, releases trapped air in lungs, reduces shortness of breath, calms anxiety',
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },

  // ANKLE/FOOT EXERCISES - Prevent blood clots
  {
    name: 'Ankle Pumps',
    description: 'Foot flexion and extension to promote circulation',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Lie or sit with legs extended\n2. Point toes away from body\n3. Hold for 2 seconds\n4. Pull toes toward body\n5. Hold for 2 seconds\n6. Repeat smoothly',
    recoveryBenefit: 'Prevents dangerous blood clots (DVT), promotes blood return to heart, reduces leg swelling, maintains ankle mobility',
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: 3,
    isActive: true,
  },
  {
    name: 'Ankle Circles',
    description: 'Circular ankle movements to improve circulation',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Lie or sit with legs extended\n2. Rotate right ankle in clockwise circles\n3. Complete 10 circles\n4. Reverse to counterclockwise for 10 circles\n5. Switch to left ankle and repeat',
    recoveryBenefit: 'Prevents blood clots, reduces ankle stiffness from bed rest, improves lower leg circulation critical for heart function',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 3,
    isActive: true,
  },

  // GENTLE ROM EXERCISES
  {
    name: 'Seated Arm Raises (Assisted)',
    description: 'Gentle shoulder movement with arm support',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: 4,
    contraindications: 'Do not raise arms above shoulder level weeks 1-2, avoid if sternum instability',
    instructions: '1. Sit with back supported\n2. Support right arm with left hand\n3. Slowly raise right arm forward to shoulder level only\n4. Hold 2 seconds\n5. Lower slowly\n6. Repeat with left arm',
    recoveryBenefit: 'Maintains shoulder mobility without straining healing sternum, prevents frozen shoulder from immobility',
    defaultSets: 2,
    defaultReps: 5,
    defaultDuration: 3,
    isActive: true,
  },
  {
    name: 'Shoulder Shrugs',
    description: 'Gentle shoulder elevation to relieve tension',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Sit or stand with arms at sides\n2. Raise both shoulders toward ears\n3. Hold for 3 seconds\n4. Release and relax shoulders down\n5. Feel tension release',
    recoveryBenefit: 'Relieves neck and shoulder tension from positioning during surgery, improves upper body circulation, reduces muscle guarding',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 2,
    isActive: true,
  },

  // ========== PHASE 2: WEEKS 3-4 - EARLY RECOVERY (Light Activity, Standing Balance) ==========

  {
    name: 'Marching in Place (Seated)',
    description: 'Gentle alternating knee lifts while sitting',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'Sturdy chair',
    minPostOpWeek: 2,
    maxPostOpWeek: 4,
    instructions: '1. Sit on edge of chair with back straight\n2. Lift right knee a few inches\n3. Lower and lift left knee\n4. Alternate slowly and controlled\n5. Breathe normally throughout',
    recoveryBenefit: 'Begins cardiovascular conditioning safely, strengthens hip flexors, improves leg strength for walking, increases heart rate gradually',
    defaultSets: 2,
    defaultReps: 20,
    defaultDuration: 3,
    isActive: true,
  },
  {
    name: 'Heel Slides',
    description: 'Gentle knee bending exercise while lying down',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 2,
    maxPostOpWeek: 6,
    instructions: '1. Lie on back with legs straight\n2. Slide right heel toward buttocks, bending knee\n3. Keep foot on surface\n4. Hold for 2 seconds\n5. Slide back to straight\n6. Repeat with left leg',
    recoveryBenefit: 'Strengthens quadriceps needed for walking, improves knee flexibility, builds leg strength without stressing heart',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Seated Knee Extensions',
    description: 'Straightening knee while seated to strengthen quadriceps',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair',
    minPostOpWeek: 3,
    maxPostOpWeek: 6,
    instructions: '1. Sit with back supported, feet flat\n2. Slowly straighten right knee\n3. Hold leg parallel to ground for 3 seconds\n4. Lower slowly\n5. Repeat with left leg',
    recoveryBenefit: 'Builds quadriceps strength essential for walking and stairs, improves leg endurance, strengthens muscles that support heart function through movement',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Sit-to-Stand Practice',
    description: 'Controlled standing from seated position',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Sturdy chair',
    minPostOpWeek: 3,
    maxPostOpWeek: 6,
    instructions: '1. Sit on edge of chair, feet flat\n2. Lean forward slightly\n3. Push through legs to stand (use arms for assist if needed)\n4. Straighten to full standing\n5. Slowly lower back to sitting',
    recoveryBenefit: 'Builds functional strength for daily activities, improves leg power, increases cardiovascular demand safely, essential for independence',
    defaultSets: 2,
    defaultReps: 5,
    defaultDuration: 3,
    isActive: true,
  },
  {
    name: 'Wall Push-Ups (Modified)',
    description: 'Gentle chest and arm strengthening against wall',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Wall',
    minPostOpWeek: 4,
    maxPostOpWeek: 8,
    contraindications: 'Wait until sternum is stable, avoid if chest pain',
    instructions: '1. Stand arm\'s length from wall\n2. Place hands on wall at shoulder height\n3. Lean forward slowly, bending elbows\n4. Push back to starting position\n5. Keep body straight',
    recoveryBenefit: 'Gradually strengthens chest and arm muscles without excessive sternum stress, improves upper body function for daily tasks, builds confidence in using arms',
    defaultSets: 2,
    defaultReps: 8,
    defaultDuration: 3,
    isActive: true,
  },
  {
    name: 'Standing March',
    description: 'Alternating knee lifts while standing with support',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair or counter for balance',
    minPostOpWeek: 3,
    maxPostOpWeek: 6,
    instructions: '1. Stand with hand on support for balance\n2. Lift right knee to comfortable height\n3. Lower and place foot down\n4. Lift left knee\n5. Continue alternating at comfortable pace',
    recoveryBenefit: 'Increases heart rate safely, improves balance and coordination, strengthens hip flexors, builds cardiovascular endurance',
    defaultSets: 2,
    defaultReps: 20,
    defaultDuration: 3,
    isActive: true,
  },

  // FLEXIBILITY - Critical for maintaining ROM
  {
    name: 'Neck Rotation Stretch',
    description: 'Gentle neck turns to relieve tension',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 2,
    maxPostOpWeek: null,
    instructions: '1. Sit with good posture\n2. Slowly turn head to look over right shoulder\n3. Hold for 10 seconds\n4. Return to center\n5. Turn to look over left shoulder\n6. Hold for 10 seconds',
    recoveryBenefit: 'Reduces neck stiffness from bed rest, improves range of motion, relieves tension from surgical positioning',
    defaultSets: 2,
    defaultReps: 5,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Shoulder Rolls',
    description: 'Circular shoulder movements to improve mobility',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 2,
    maxPostOpWeek: null,
    instructions: '1. Sit or stand with arms relaxed\n2. Roll shoulders forward in circular motion - 5 times\n3. Roll shoulders backward in circular motion - 5 times\n4. Move slowly and smoothly',
    recoveryBenefit: 'Prevents shoulder stiffness, improves circulation to upper body, reduces muscle tension from protective posturing',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 3,
    isActive: true,
  },
  {
    name: 'Wrist Circles',
    description: 'Rotating wrists to maintain flexibility',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Extend arms forward at shoulder height (or rest elbows on armrests)\n2. Make circles with hands at wrist\n3. 10 circles clockwise\n4. 10 circles counterclockwise',
    recoveryBenefit: 'Maintains wrist flexibility for daily activities, improves circulation to hands and arms',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 2,
    isActive: true,
  },

  // ========== PHASE 3: WEEKS 5-6 - BUILDING ENDURANCE (Light Cardio, Basic Resistance) ==========

  {
    name: 'Slow Walking (Indoor)',
    description: 'Controlled pace walking for cardiovascular conditioning',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 3,
    maxPostOpWeek: null,
    instructions: '1. Walk at comfortable pace indoors\n2. Maintain steady breathing\n3. Start with 5 minutes\n4. Increase by 1-2 minutes per session\n5. Stop if experiencing chest pain, dizziness, or severe shortness of breath',
    recoveryBenefit: 'Cornerstone of cardiac rehabilitation - strengthens heart muscle, improves circulation, lowers blood pressure, builds endurance safely',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 10,
    isActive: true,
  },
  {
    name: 'Treadmill Walking (Level)',
    description: 'Controlled treadmill walking at flat grade',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'Treadmill',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Start at slow speed (1.5-2 mph)\n2. Hold side rails initially if needed\n3. Maintain upright posture\n4. Progress speed gradually\n5. Monitor heart rate stays in target zone',
    recoveryBenefit: 'Controlled cardiovascular conditioning, consistent pace helps regulate heart rate, builds endurance for daily activities',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 15,
    isActive: true,
  },
  {
    name: 'Stationary Bike (Low Resistance)',
    description: 'Gentle cycling for cardiovascular fitness',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'Stationary bike',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Adjust seat to proper height\n2. Start with zero or minimal resistance\n3. Pedal at comfortable, steady pace\n4. Keep RPM between 50-60\n5. Maintain proper posture',
    recoveryBenefit: 'Low-impact cardio strengthens heart without joint stress, improves leg strength and endurance, excellent for weight management',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 15,
    isActive: true,
  },
  {
    name: 'Step-Ups (Low Step)',
    description: 'Stepping up onto low platform',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: '4-6 inch step or stair',
    minPostOpWeek: 5,
    maxPostOpWeek: 8,
    instructions: '1. Face a low step\n2. Step up with right foot\n3. Bring left foot up to meet right\n4. Step down with right foot\n5. Bring left foot down\n6. Use handrail if available',
    recoveryBenefit: 'Simulates stair climbing for daily function, strengthens legs for real-world activities, increases cardiovascular demand gradually',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Standing Hip Abduction',
    description: 'Leg lifts to the side for hip strength',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair for balance',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Stand with hand on chair for support\n2. Keep standing leg slightly bent\n3. Lift right leg out to side, keeping toe forward\n4. Lift only to comfortable height\n5. Lower slowly\n6. Repeat then switch legs',
    recoveryBenefit: 'Strengthens hip stabilizers for balance and walking, improves lateral stability, prevents falls',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Standing Hip Extension',
    description: 'Backward leg lifts for glute strength',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair for balance',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Stand facing chair, hands on back for support\n2. Keep standing leg slightly bent\n3. Extend right leg straight back\n4. Squeeze glutes\n5. Hold 2 seconds\n6. Lower and repeat, then switch',
    recoveryBenefit: 'Strengthens glutes and hamstrings crucial for walking and standing, improves posterior chain strength, supports lower back',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Seated Row (Resistance Band)',
    description: 'Pulling motion with elastic band for back strength',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Resistance band',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Sit with legs extended, band around feet\n2. Hold ends of band in each hand\n3. Sit upright with shoulders back\n4. Pull band toward body, squeezing shoulder blades\n5. Return slowly to start',
    recoveryBenefit: 'Strengthens upper back to improve posture post-surgery, counteracts forward shoulder position, builds functional pulling strength',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Bicep Curls (Light Weight)',
    description: 'Arm curls with 1-2 lb weights',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: '1-2 lb dumbbells or cans',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Stand or sit with weights in hands\n2. Arms at sides, palms forward\n3. Bend elbows, curl weights to shoulders\n4. Keep elbows at sides\n5. Lower slowly to start',
    recoveryBenefit: 'Builds arm strength for daily tasks like carrying groceries, maintains upper body function, improves confidence in arm use',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },

  // ========== PHASE 4: WEEKS 7-8 - MODERATE INTENSITY (Increased Duration and Resistance) ==========

  {
    name: 'Brisk Walking',
    description: 'Faster-paced walking for cardiovascular fitness',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Walk at pace where you can talk but not sing\n2. Swing arms naturally\n3. Maintain good posture\n4. Breathe rhythmically\n5. Aim for 20-30 minutes',
    recoveryBenefit: 'Significantly improves cardiovascular fitness, strengthens heart muscle, reduces risk of future cardiac events, helps control weight and blood pressure',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 25,
    isActive: true,
  },
  {
    name: 'Incline Walking (Treadmill)',
    description: 'Walking on slight incline for increased intensity',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Treadmill',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Start at 0% incline, warm up 5 min\n2. Gradually increase incline to 2-3%\n3. Maintain steady pace\n4. Monitor heart rate and breathing\n5. Decrease incline if becomes too difficult',
    recoveryBenefit: 'Increases cardiovascular demand safely, builds leg strength, simulates outdoor walking conditions, improves exercise capacity',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 20,
    isActive: true,
  },
  {
    name: 'Stationary Bike (Moderate Resistance)',
    description: 'Cycling with increased resistance',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Stationary bike',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Warm up 5 minutes at low resistance\n2. Increase to moderate resistance level\n3. Maintain RPM 60-70\n4. Cycle for 20-25 minutes\n5. Cool down 5 minutes at low resistance',
    recoveryBenefit: 'Builds cardiovascular endurance, strengthens legs without joint impact, excellent calorie burning for weight management',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 25,
    isActive: true,
  },
  {
    name: 'Elliptical Training',
    description: 'Low-impact cardio machine using arms and legs',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Elliptical machine',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Start with low resistance\n2. Use both arm handles and leg pedals\n3. Maintain upright posture\n4. Smooth, controlled movements\n5. Build up duration gradually',
    recoveryBenefit: 'Full-body cardio workout, low impact on joints, engages both upper and lower body, excellent for endurance building',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 20,
    isActive: true,
  },
  {
    name: 'Mini Squats',
    description: 'Quarter squats for leg strength',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Chair for support',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Stand with feet shoulder-width apart\n2. Hold chair for balance if needed\n3. Bend knees and hips slightly (quarter squat)\n4. Keep chest up and weight in heels\n5. Return to standing',
    recoveryBenefit: 'Strengthens major leg muscles (quads, glutes, hamstrings) essential for daily activities, improves functional strength, builds bone density',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Standing Calf Raises',
    description: 'Rising on toes to strengthen calves',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Chair or wall for balance',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Stand with feet hip-width apart\n2. Hold support for balance\n3. Rise up on toes as high as comfortable\n4. Hold for 2 seconds\n5. Lower heels to floor slowly',
    recoveryBenefit: 'Strengthens calves for walking and balance, improves circulation from legs back to heart (calf muscle pump), prevents ankle weakness',
    defaultSets: 2,
    defaultReps: 15,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Lat Pulldown (Light Weight)',
    description: 'Overhead pulling motion with cable or band',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Resistance band or cable machine',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Sit with band secured overhead or use machine\n2. Grasp handles with arms extended\n3. Pull down to chest level\n4. Squeeze shoulder blades together\n5. Return slowly to start',
    recoveryBenefit: 'Strengthens lat muscles important for upper body function, improves pulling strength for daily tasks, builds back strength',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Overhead Press (Light Weight)',
    description: 'Pressing light weights overhead',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: '2-5 lb dumbbells',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    contraindications: 'Only after full sternum healing, avoid if shoulder pain',
    instructions: '1. Stand or sit with weights at shoulder level\n2. Press weights overhead until arms extended\n3. Keep core engaged\n4. Lower slowly to shoulders\n5. Breathe out on press up',
    recoveryBenefit: 'Builds shoulder strength for overhead activities (reaching shelves, etc.), strengthens deltoids and triceps, improves functional upper body capacity',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Chest Fly (Light Weight)',
    description: 'Opening arms with light weights for chest',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: '2-3 lb dumbbells',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    contraindications: 'Only after complete sternum healing (8+ weeks), stop if chest discomfort',
    instructions: '1. Lie on bench or floor, knees bent\n2. Hold light weights above chest, arms slightly bent\n3. Open arms out to sides in arc motion\n4. Feel chest stretch\n5. Bring back to start',
    recoveryBenefit: 'Carefully strengthens chest muscles after sternum healing, improves chest flexibility, builds confidence in using chest muscles',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },

  // CORE STRENGTHENING - Important but must be gentle
  {
    name: 'Abdominal Bracing',
    description: 'Isometric core engagement',
    category: 'core',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Lie on back with knees bent\n2. Tighten abdominal muscles (as if bracing for punch)\n3. Hold for 5-10 seconds while breathing normally\n4. Do not hold breath\n5. Relax and repeat',
    recoveryBenefit: 'Activates core muscles without stressing sternum, improves core stability for daily movements, supports back health',
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Pelvic Tilts',
    description: 'Gentle lower back and core activation',
    category: 'core',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Lie on back, knees bent, feet flat\n2. Flatten lower back against floor by tilting pelvis\n3. Engage core muscles\n4. Hold for 5 seconds\n5. Release and repeat',
    recoveryBenefit: 'Strengthens core without crunches, protects lower back, improves posture, safe for healing sternum',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Bird Dog (Modified)',
    description: 'Alternating arm and leg extensions on hands and knees',
    category: 'core',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Start on hands and knees\n2. Extend right arm forward while extending left leg back\n3. Keep back flat and core engaged\n4. Hold 5 seconds\n5. Return and switch sides',
    recoveryBenefit: 'Improves balance and core stability, strengthens back muscles, enhances coordination, functional strength',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Standing Core Rotation',
    description: 'Twisting motion to engage obliques',
    category: 'core',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Stand with feet shoulder-width\n2. Hold hands at chest level\n3. Rotate torso to right, keeping hips forward\n4. Return to center\n5. Rotate to left',
    recoveryBenefit: 'Strengthens oblique muscles for rotation movements, improves flexibility for daily activities like reaching, looking behind while driving',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },

  // ========== PHASE 5: WEEKS 9-10 - PROGRESSIVE TRAINING (Higher Intensity Options) ==========

  {
    name: 'Interval Walking',
    description: 'Alternating between normal and brisk pace',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Warm up 5 minutes normal pace\n2. Walk briskly 2 minutes\n3. Walk normal pace 3 minutes\n4. Repeat pattern 4-5 times\n5. Cool down 5 minutes',
    recoveryBenefit: 'Increases cardiovascular fitness faster than steady pace, improves heart\'s ability to handle varying demands, burns more calories',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 30,
    isActive: true,
  },
  {
    name: 'Stair Climbing',
    description: 'Climbing actual stairs at controlled pace',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Staircase with handrail',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Use handrail for safety\n2. Climb one flight at comfortable pace\n3. Rest at top if needed\n4. Walk down slowly\n5. Repeat for 10-15 minutes total',
    recoveryBenefit: 'Excellent for cardiovascular fitness, builds leg strength, functional exercise for daily life, tests exercise capacity',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 15,
    isActive: true,
  },
  {
    name: 'Rowing Machine',
    description: 'Full-body cardio using rowing ergometer',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Rowing machine',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Sit with feet secured, knees bent\n2. Grasp handle with both hands\n3. Push with legs, then pull handle to chest\n4. Extend arms, bend knees, slide forward\n5. Maintain smooth rhythm',
    recoveryBenefit: 'Low-impact full-body workout, engages 85% of body\'s muscles, excellent cardio and strength combination, builds endurance',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 20,
    isActive: true,
  },
  {
    name: 'Lunges (Supported)',
    description: 'Forward stepping lunge with chair support',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Chair or wall for balance',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Stand with chair to side for support\n2. Step forward with right leg\n3. Lower body until front thigh parallel to ground\n4. Back knee hovers above floor\n5. Push back to start\n6. Switch legs',
    recoveryBenefit: 'Builds functional leg strength for stairs and walking, improves balance and coordination, strengthens glutes and quads independently',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Leg Press (Light Weight)',
    description: 'Pushing weight with legs on machine',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Leg press machine',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Sit with back supported, feet on platform\n2. Push platform away by extending legs\n3. Do not lock knees\n4. Lower platform slowly with control\n5. Keep back flat on pad',
    recoveryBenefit: 'Safely builds major leg muscle groups, supports weight without loading spine, improves lower body strength for activities',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Push-Ups (Incline)',
    description: 'Push-ups with hands elevated on bench',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Bench or sturdy surface',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    contraindications: 'Only with full sternum healing and no pain',
    instructions: '1. Place hands on bench shoulder-width apart\n2. Extend legs behind with straight body\n3. Lower chest to bench\n4. Push back up to start\n5. Keep core engaged throughout',
    recoveryBenefit: 'Progressively builds chest, shoulder, and arm strength, functional pushing motion for daily tasks, boosts upper body confidence',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Dumbbell Chest Press',
    description: 'Pressing weights from chest',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: '5-10 lb dumbbells',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    contraindications: 'Sternum must be completely healed',
    instructions: '1. Lie on bench with weights at chest\n2. Feet flat on floor\n3. Press weights up until arms extended\n4. Lower slowly to chest level\n5. Breathe out on press',
    recoveryBenefit: 'Rebuilds chest strength after surgery, improves pressing function for daily tasks, builds upper body power',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Tricep Dips (Supported)',
    description: 'Using chair to work back of arms',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Sturdy chair',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Sit on edge of chair, hands beside hips\n2. Slide hips forward off chair\n3. Lower body by bending elbows\n4. Lower only a few inches initially\n5. Push back up to start',
    recoveryBenefit: 'Strengthens triceps for pushing and lifting, improves arm strength for getting up from chairs, builds functional upper body power',
    defaultSets: 2,
    defaultReps: 8,
    defaultDuration: 5,
    isActive: true,
  },

  // BALANCE TRAINING - Fall prevention
  {
    name: 'Single Leg Stance',
    description: 'Standing on one leg for balance',
    category: 'balance',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair or wall nearby',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Stand near support\n2. Lift right foot a few inches off ground\n3. Balance on left leg for 10-30 seconds\n4. Lower and repeat on other leg\n5. Touch support only if losing balance',
    recoveryBenefit: 'Prevents falls which are dangerous after surgery, improves proprioception, strengthens ankle stabilizers, boosts confidence',
    defaultSets: 3,
    defaultReps: 5,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Heel-to-Toe Walk',
    description: 'Tandem walking for balance',
    category: 'balance',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Walk in straight line\n2. Place heel of front foot directly against toes of back foot\n3. Walk 10-20 steps\n4. Use wall or counter if needed for balance\n5. Focus on point ahead',
    recoveryBenefit: 'Challenges balance system, improves coordination, strengthens core stabilizers, reduces fall risk',
    defaultSets: 3,
    defaultReps: 1,
    defaultDuration: 3,
    isActive: true,
  },
  {
    name: 'Standing Knee Raises (Balance)',
    description: 'Lifting knee while balancing',
    category: 'balance',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Stand without support (or light fingertip touch)\n2. Lift right knee to hip level\n3. Hold for 5 seconds\n4. Lower slowly\n5. Repeat with left leg',
    recoveryBenefit: 'Dynamic balance training, improves stability during movement like walking, strengthens hip flexors and standing leg',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Side Leg Raises (Balance Challenge)',
    description: 'Lifting leg to side without support',
    category: 'balance',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Stand without holding support\n2. Lift right leg out to side\n3. Hold for 3 seconds\n4. Lower slowly\n5. Maintain upright posture throughout\n6. Switch legs',
    recoveryBenefit: 'Challenges lateral stability, strengthens hip abductors critical for walking, improves balance confidence',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },

  // ADVANCED FLEXIBILITY
  {
    name: 'Cat-Cow Stretch',
    description: 'Spinal mobility on hands and knees',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Start on hands and knees\n2. Arch back up like cat, chin to chest\n3. Hold 5 seconds\n4. Let belly drop, lift chin (cow)\n5. Hold 5 seconds\n6. Flow between positions',
    recoveryBenefit: 'Improves spinal flexibility, relieves back tension, gentle core activation, improves posture',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Hamstring Stretch (Seated)',
    description: 'Stretching back of thigh',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Sit on edge of chair\n2. Extend right leg straight, heel on floor\n3. Keep left foot flat\n4. Lean forward from hips until stretch in back of right thigh\n5. Hold 20-30 seconds\n6. Switch legs',
    recoveryBenefit: 'Relieves tight hamstrings from sitting, improves flexibility for bending and walking, reduces lower back strain',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Quadriceps Stretch (Standing)',
    description: 'Stretching front of thigh',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair or wall for balance',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Stand with support nearby\n2. Bend right knee, bringing heel toward buttocks\n3. Grasp right ankle with right hand\n4. Keep knees together\n5. Feel stretch in front of thigh\n6. Hold 20-30 seconds',
    recoveryBenefit: 'Stretches major thigh muscle often tight from sitting and exercise, improves knee flexibility, reduces muscle imbalances',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Hip Flexor Stretch',
    description: 'Stretching front of hip',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Kneel on right knee, left foot forward (lunge position)\n2. Keep torso upright\n3. Shift weight forward\n4. Feel stretch in front of right hip\n5. Hold 20-30 seconds\n6. Switch legs',
    recoveryBenefit: 'Relieves tight hip flexors from sitting, improves posture, reduces lower back strain, enhances walking mechanics',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Calf Stretch (Wall)',
    description: 'Stretching calf muscles against wall',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'Wall',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Face wall, hands on wall at shoulder height\n2. Step right foot back, keep leg straight\n3. Keep heel on ground\n4. Bend left knee, lean toward wall\n5. Feel stretch in right calf\n6. Hold 20-30 seconds',
    recoveryBenefit: 'Prevents calf tightness from walking exercise, improves ankle flexibility, reduces risk of Achilles tendon issues',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Chest Doorway Stretch',
    description: 'Opening chest muscles in doorway',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'Doorway',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    contraindications: 'Only after complete sternum healing, be very gentle',
    instructions: '1. Stand in doorway\n2. Place forearms on door frame at shoulder height\n3. Step forward with one foot\n4. Feel gentle stretch across chest\n5. Do not overstretch\n6. Hold 20 seconds',
    recoveryBenefit: 'Gently stretches chest muscles that may be tight from surgery and protective posturing, improves posture, opens breathing',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Upper Back Stretch',
    description: 'Stretching between shoulder blades',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Sit or stand\n2. Clasp hands in front at chest level\n3. Push hands forward, rounding upper back\n4. Let chin drop toward chest\n5. Feel stretch between shoulder blades\n6. Hold 20 seconds',
    recoveryBenefit: 'Relieves upper back tension, counteracts forward shoulder posture, improves thoracic spine mobility',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },

  // ========== PHASE 6: WEEKS 11-12 - FINAL PHASE (Independence, Lifelong Habits) ==========

  {
    name: 'Outdoor Walking',
    description: 'Walking outside on varied terrain',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Choose safe route with sidewalks\n2. Walk at brisk pace for 30-45 minutes\n3. Include some hills if able\n4. Maintain proper posture\n5. Monitor for any symptoms',
    recoveryBenefit: 'Real-world cardiovascular conditioning, varied terrain challenges balance and strength, sunshine and fresh air benefit mood and vitamin D',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 35,
    isActive: true,
  },
  {
    name: 'Swimming (Easy Pace)',
    description: 'Swimming laps at comfortable pace',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Pool access',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    contraindications: 'Sternum incision must be completely healed and cleared by surgeon',
    instructions: '1. Swim laps at easy pace\n2. Use freestyle, backstroke, or any comfortable stroke\n3. Rest between laps as needed\n4. Start with 10-15 minutes\n5. Build up gradually',
    recoveryBenefit: 'Excellent low-impact full-body cardio, water supports body weight, works all major muscle groups, very safe for joints',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 20,
    isActive: true,
  },
  {
    name: 'Water Aerobics',
    description: 'Group exercise class in pool',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Pool access',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    contraindications: 'Full healing of all incisions required',
    instructions: '1. Join a water aerobics class\n2. Follow instructor for movements\n3. Work at your own pace\n4. Water provides resistance and support\n5. Typically 45-60 minute classes',
    recoveryBenefit: 'Social exercise environment, low-impact full-body workout, water resistance builds strength, fun and motivating',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 45,
    isActive: true,
  },
  {
    name: 'Group Exercise Class',
    description: 'Cardiac rehab or senior fitness class',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Class setting',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    instructions: '1. Join appropriate level class\n2. Inform instructor of cardiac history\n3. Modify exercises as needed\n4. Work at sustainable pace\n5. Enjoy social aspect',
    recoveryBenefit: 'Social support critical for long-term adherence, professional guidance, full-body workout, accountability and motivation',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 45,
    isActive: true,
  },
  {
    name: 'Light Jogging Intervals',
    description: 'Brief jogging periods mixed with walking',
    category: 'cardio',
    difficulty: 'advanced',
    equipmentNeeded: 'None',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    contraindications: 'Only with physician approval, sternum must be fully healed',
    instructions: '1. Warm up with 10 minutes walking\n2. Jog slowly for 1 minute\n3. Walk 4 minutes\n4. Repeat 4-5 times\n5. Cool down 5 minutes walking',
    recoveryBenefit: 'For patients cleared to advance to jogging, provides higher intensity cardio, builds cardiovascular capacity, increases exercise options',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 30,
    isActive: true,
  },
  {
    name: 'Full Squats',
    description: 'Complete squats to 90 degrees',
    category: 'lower_body',
    difficulty: 'advanced',
    equipmentNeeded: 'None',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    instructions: '1. Stand with feet shoulder-width apart\n2. Lower body by bending knees and hips\n3. Go down until thighs parallel to ground\n4. Keep chest up, weight in heels\n5. Push back up to standing',
    recoveryBenefit: 'Builds full leg strength for all activities, improves functional capacity, strengthens major muscle groups, boosts metabolism',
    defaultSets: 3,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Deadlift (Light Weight)',
    description: 'Lifting weight from floor with proper form',
    category: 'lower_body',
    difficulty: 'advanced',
    equipmentNeeded: '10-20 lb weight or barbell',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    contraindications: 'Only with complete healing and professional guidance',
    instructions: '1. Stand with weight on floor in front\n2. Bend at hips and knees to grasp weight\n3. Keep back straight, core engaged\n4. Lift by straightening legs and hips\n5. Lower with control',
    recoveryBenefit: 'Functional movement for safe lifting, strengthens entire posterior chain (back, glutes, hamstrings), prevents back injury',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Push-Ups (Standard)',
    description: 'Full push-ups from floor',
    category: 'upper_body',
    difficulty: 'advanced',
    equipmentNeeded: 'None',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    contraindications: 'Complete sternum healing required',
    instructions: '1. Start in plank position, hands under shoulders\n2. Keep body straight from head to heels\n3. Lower chest toward floor\n4. Push back up to start\n5. Core engaged throughout',
    recoveryBenefit: 'Excellent indicator of upper body strength recovery, builds chest/shoulder/arm strength, functional pushing power',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Pull-Ups (Assisted)',
    description: 'Pulling body up using assistance',
    category: 'upper_body',
    difficulty: 'advanced',
    equipmentNeeded: 'Assisted pull-up machine or resistance band',
    minPostOpWeek: 12,
    maxPostOpWeek: null,
    instructions: '1. Grasp bar with overhand grip\n2. Use assistance as needed\n3. Pull body up until chin over bar\n4. Lower with control\n5. Build up gradually',
    recoveryBenefit: 'Ultimate pulling strength exercise, builds back and arm strength, improves grip strength, shows full recovery',
    defaultSets: 2,
    defaultReps: 6,
    defaultDuration: 5,
    isActive: true,
  },

  // CORE ADVANCED
  {
    name: 'Plank',
    description: 'Holding body straight in plank position',
    category: 'core',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Start on forearms and toes\n2. Keep body in straight line from head to heels\n3. Engage core and glutes\n4. Hold for 15-60 seconds\n5. Breathe normally',
    recoveryBenefit: 'Best core strengthening exercise, stabilizes spine, improves posture, builds endurance in core muscles',
    defaultSets: 3,
    defaultReps: 1,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Side Plank',
    description: 'Plank on side to target obliques',
    category: 'core',
    difficulty: 'advanced',
    equipmentNeeded: 'None',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    instructions: '1. Lie on side, forearm on ground\n2. Stack feet or stagger for easier\n3. Lift hips off ground\n4. Keep body straight from head to feet\n5. Hold 15-30 seconds each side',
    recoveryBenefit: 'Strengthens obliques and lateral core stability, improves balance, prevents side-to-side collapse, functional strength',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Mountain Climbers (Slow)',
    description: 'Alternating knee drives in plank',
    category: 'core',
    difficulty: 'advanced',
    equipmentNeeded: 'None',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    instructions: '1. Start in plank position\n2. Bring right knee toward chest\n3. Return to plank\n4. Bring left knee toward chest\n5. Alternate in controlled manner',
    recoveryBenefit: 'Dynamic core exercise with cardio component, builds core strength and endurance, improves coordination',
    defaultSets: 2,
    defaultReps: 20,
    defaultDuration: 5,
    isActive: true,
  },

  // BALANCE ADVANCED
  {
    name: 'Single Leg Deadlift',
    description: 'Balancing on one leg while hinging forward',
    category: 'balance',
    difficulty: 'advanced',
    equipmentNeeded: 'None or light weight',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    instructions: '1. Stand on right leg\n2. Hinge forward at hip, extending left leg behind\n3. Reach toward floor with hands\n4. Keep back straight\n5. Return to standing\n6. Switch legs',
    recoveryBenefit: 'Advanced balance and strength combination, strengthens glutes and hamstrings, improves proprioception, functional movement',
    defaultSets: 2,
    defaultReps: 8,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Bosu Ball Squats',
    description: 'Squatting on unstable surface',
    category: 'balance',
    difficulty: 'advanced',
    equipmentNeeded: 'Bosu ball or balance disc',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    instructions: '1. Stand on Bosu ball (flat side down)\n2. Find balance\n3. Perform squat on unstable surface\n4. Use arms for balance\n5. Return to standing',
    recoveryBenefit: 'Challenges balance and stability systems, strengthens ankle and knee stabilizers, improves proprioception, reduces fall risk',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },

  // FUNCTIONAL MOVEMENTS
  {
    name: 'Carrying Objects (Farmer\'s Walk)',
    description: 'Walking while carrying weights',
    category: 'upper_body',
    difficulty: 'advanced',
    equipmentNeeded: 'Dumbbells or weighted objects',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    instructions: '1. Hold moderate weight in each hand\n2. Stand upright with good posture\n3. Walk forward 20-30 steps\n4. Keep shoulders back and core engaged\n5. Turn and walk back',
    recoveryBenefit: 'Mimics carrying groceries and real-life activities, builds grip strength, improves core stability, functional strength',
    defaultSets: 3,
    defaultReps: 1,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Reaching and Lifting Practice',
    description: 'Practicing overhead reaching with light object',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Light object (1-2 lbs)',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    instructions: '1. Start with object at waist level\n2. Lift object overhead reaching high\n3. Lower slowly to waist\n4. Place on low surface\n5. Lift back to waist\n6. Repeat sequence',
    recoveryBenefit: 'Practices functional movements needed for daily life (reaching shelves, putting things away), builds confidence in daily activities',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Stair Step Patterns',
    description: 'Various stepping patterns on stairs',
    category: 'cardio',
    difficulty: 'advanced',
    equipmentNeeded: 'Staircase',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    instructions: '1. Step up two steps at a time\n2. Step down one at a time\n3. Side step up stairs\n4. Use handrail for safety\n5. Vary patterns for challenge',
    recoveryBenefit: 'Advanced functional training for stairs, builds confidence in varied stair situations, improves leg strength and coordination',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 10,
    isActive: true,
  },
  {
    name: 'Agility Ladder Drills',
    description: 'Foot patterns through ladder on ground',
    category: 'cardio',
    difficulty: 'advanced',
    equipmentNeeded: 'Agility ladder or chalk marks',
    minPostOpWeek: 12,
    maxPostOpWeek: null,
    instructions: '1. Lay ladder flat on ground\n2. Step through squares with quick feet\n3. Try various patterns (one foot each, both feet, lateral)\n4. Start slow, increase speed gradually\n5. Focus on coordination',
    recoveryBenefit: 'Improves coordination and agility, challenges cardiovascular system, fun variation, builds confidence in quick movements',
    defaultSets: 3,
    defaultReps: 3,
    defaultDuration: 10,
    isActive: true,
  },
];

export async function seedExercises() {
  try {
    console.log('Seeding exercises...');

    const exerciseCount = await Exercise.count();
    if (exerciseCount > 0) {
      console.log(`Found ${exerciseCount} existing exercises. Clearing...`);
      await Exercise.destroy({ where: {} });
      console.log('Cleared all existing exercises.');
    }

    await Exercise.bulkCreate(exercises);
    console.log(`✅ Successfully seeded ${exercises.length} exercises`);
  } catch (error) {
    console.error('Error seeding exercises:', error);
    throw error;
  }
}

if (require.main === module) {
  seedExercises()
    .then(() => {
      console.log('Exercise seeding completed');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Exercise seeding failed:', error);
      process.exit(1);
    });
}
