import Exercise from '../models/Exercise';

type ExerciseCategory = 'upper_body' | 'lower_body' | 'cardio' | 'flexibility' | 'balance' | 'breathing' | 'core';
type ExerciseDifficulty = 'beginner' | 'intermediate' | 'advanced';

interface ExerciseSeedData {
  name: string;
  description: string;
  category: ExerciseCategory;
  difficulty: ExerciseDifficulty;
  equipmentNeeded: string;
  minPostOpWeek: number;
  maxPostOpWeek: number | null;
  contraindications?: string;
  instructions: string;
  recoveryBenefit: string;
  defaultSets: number;
  defaultReps: number;
  defaultDuration: number;
  isActive: boolean;
  videoUrl?: string;
  imageUrl?: string;
  formTips?: string;
  modifications?: string;
}

const exercises: ExerciseSeedData[] = [
  // ========== PHASE 1: WEEKS 1-2 - IMMEDIATE POST-OP (Very Gentle, Bed/Chair Exercises) ==========

  // BREATHING EXERCISES - Critical for lung function
  {
    name: 'Deep Breathing Exercise',
    description: 'Slow, controlled deep breaths to expand lungs and prevent complications',
    category: 'breathing',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    contraindications: 'Severe chest pain, dizziness, shortness of breath at rest',
    instructions: '1. Sit upright with back supported\n2. Inhale slowly through nose for 4 counts\n3. Hold breath for 2 counts\n4. Exhale slowly through mouth for 6 counts\n5. Rest and repeat',
    recoveryBenefit: 'Prevents pneumonia and lung complications, improves oxygen delivery to healing heart tissue, reduces risk of blood clots',
    defaultSets: 4,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    videoUrl: 'https://www.youtube.com/watch?v=aXItOY0sLRY',
    imageUrl: 'https://i.ytimg.com/vi/aXItOY0sLRY/maxresdefault.jpg',
    formTips: 'Keep shoulders relaxed and down, not hunched. Focus on expanding belly, not chest wall. Never force the breath or hold it if uncomfortable. Stop immediately if you feel lightheaded, dizzy, or experience chest pain. Breathe at your own comfortable pace - counts are guidelines only.',
    modifications: 'Easier: Start with just 5 breaths per set, reduce hold time to 1 count or eliminate hold completely, use shorter count (2-2-4 instead of 4-2-6). Harder: Increase hold time to 3-4 counts, add gentle arm raises during inhalation, increase to 6-8-8 count. Can be done lying down if sitting is uncomfortable, or standing with back against wall for support.',
  },
  {
    name: 'Incentive Spirometer',
    description: 'Device-assisted breathing to prevent lung complications',
    category: 'breathing',
    difficulty: 'beginner',
    equipmentNeeded: 'Incentive spirometer',
    minPostOpWeek: 1,
    maxPostOpWeek: 6,
    instructions: '1. Sit upright\n2. Exhale normally\n3. Seal lips around mouthpiece\n4. Inhale slowly and deeply\n5. Hold at target level for 3-5 seconds\n6. Exhale slowly and rest',
    recoveryBenefit: 'Expands lung capacity, prevents atelectasis (lung collapse), improves blood oxygenation critical for healing',
    defaultSets: 1,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    videoUrl: 'https://www.youtube.com/watch?v=ZJhGDLhfxys',
    imageUrl: 'https://i.ytimg.com/vi/ZJhGDLhfxys/maxresdefault.jpg',
    formTips: 'Sit upright with back fully supported. Create complete seal around mouthpiece. Inhale slowly and steadily - quick gasps won\'t expand lungs properly. Watch the ball or indicator rise smoothly. If you cough during or after, support your sternum with a pillow. Take breaks between repetitions to avoid hyperventilation.',
    modifications: 'Easier: Aim for lower target volume initially, hold breath for only 2 seconds, take longer rests between reps (30-60 seconds). Harder: Increase target volume as tolerated, hold for full 5 seconds, reduce rest time between reps. Can be done semi-reclined if sitting upright is too challenging, but avoid lying completely flat.',
  },
  {
    name: 'Diaphragmatic Breathing',
    description: 'Belly breathing to strengthen diaphragm and reduce chest strain',
    category: 'breathing',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Lie on back or sit comfortably\n2. Place one hand on chest, one on belly\n3. Inhale through nose - belly rises, chest stays still\n4. Exhale through pursed lips - belly falls\n5. Focus on belly movement only',
    recoveryBenefit: 'Strengthens primary breathing muscle, reduces work on healing chest muscles, improves breathing efficiency and oxygen intake',
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    videoUrl: 'https://www.youtube.com/watch?v=nYIcbL9FO4s',
    imageUrl: 'https://i.ytimg.com/vi/nYIcbL9FO4s/maxresdefault.jpg',
    formTips: 'Keep chest hand relatively still while belly hand rises with each breath. Don\'t force belly out - let diaphragm naturally expand it. Exhale longer than you inhale for better lung emptying. If lying down, bend knees to reduce abdominal tension. Stop if you feel dizzy or short of breath.',
    modifications: 'Easier: Start with just 5 breaths, practice for 2 minutes total, lie flat if sitting is tiring. Harder: Add light weight (book) on belly for resistance, extend to 15 breaths per set, combine with relaxation meditation. Can be done seated in chair with back support, semi-reclined, or fully lying down based on comfort.',
  },
  {
    name: 'Pursed Lip Breathing',
    description: 'Controlled exhalation technique to improve lung emptying',
    category: 'breathing',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Relax neck and shoulders\n2. Inhale through nose for 2 counts\n3. Purse lips as if whistling\n4. Exhale slowly through pursed lips for 4 counts\n5. Keep exhalation twice as long as inhalation',
    recoveryBenefit: 'Improves ventilation, releases trapped air in lungs, reduces shortness of breath, calms anxiety',
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    videoUrl: 'https://www.youtube.com/watch?v=FNxFqJuGneg',
    imageUrl: 'https://i.ytimg.com/vi/FNxFqJuGneg/maxresdefault.jpg',
    formTips: 'Purse lips loosely, not tightly clenched. Let air flow out naturally without forcing. Keep shoulders and neck completely relaxed. Focus on making exhale gentle and controlled, not hard. Use anytime you feel short of breath. This should feel calming, not strenuous.',
    modifications: 'Easier: Use 1-2 count ratio instead of 2-4, reduce to 5 breaths per set, take longer breaks. Harder: Extend to 3-6 count ratio, add 4-second pause between breaths, combine with gentle walking. Can be done in any position - sitting, standing, lying down, or even during light activity when breathless.',
  },

  // ANKLE/FOOT EXERCISES - Prevent blood clots
  {
    name: 'Ankle Pumps',
    description: 'Foot flexion and extension to promote circulation',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Lie or sit with legs extended\n2. Point toes away from body\n3. Hold for 2 seconds\n4. Pull toes toward body\n5. Hold for 2 seconds\n6. Repeat smoothly',
    recoveryBenefit: 'Prevents dangerous blood clots (DVT), promotes blood return to heart, reduces leg swelling, maintains ankle mobility',
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: 3,
    isActive: true,
    videoUrl: 'https://www.youtube.com/watch?v=MKxON8FZKps',
    imageUrl: 'https://i.ytimg.com/vi/MKxON8FZKps/maxresdefault.jpg',
    formTips: 'Move only at the ankle, keep legs still and relaxed. Point and flex through full range of motion without pain. Breathe normally throughout - don\'t hold breath. Move smoothly and rhythmically. Can be done hourly throughout the day, especially important during bed rest.',
    modifications: 'Easier: Reduce to 10 reps per set, shorten hold time to 1 second, move one foot at a time. Harder: Increase to 20 reps per set, add resistance band around feet, perform both feet simultaneously. Can be done in bed, recliner, wheelchair, or regular chair.',
  },
  {
    name: 'Ankle Circles',
    description: 'Circular ankle movements to improve circulation',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Lie or sit with legs extended\n2. Rotate right ankle in clockwise circles\n3. Complete 10 circles\n4. Reverse to counterclockwise for 10 circles\n5. Switch to left ankle and repeat',
    recoveryBenefit: 'Prevents blood clots, reduces ankle stiffness from bed rest, improves lower leg circulation critical for heart function',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 3,
    isActive: true,
    videoUrl: 'https://www.youtube.com/watch?v=DWB-AKoTFsE',
    imageUrl: 'https://i.ytimg.com/vi/DWB-AKoTFsE/maxresdefault.jpg',
    formTips: 'Make circles as large as comfortable without pain. Move slowly and controlled - quality over speed. Keep leg and knee still, movement only at ankle. Breathe continuously, never hold breath. If you feel calf cramping, stop and gently stretch.',
    modifications: 'Easier: Make smaller circles, reduce to 5 circles each direction, do one ankle at a time with rest between. Harder: Increase to 15 circles each direction, add ankle weights, draw alphabet with toes. Can be done sitting up in bed, in chair, or lying down.',
  },

  // GENTLE ROM EXERCISES
  {
    name: 'Seated Arm Raises (Assisted)',
    description: 'Gentle shoulder movement with arm support',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: 4,
    contraindications: 'Do not raise arms above shoulder level weeks 1-2, avoid if sternum instability',
    instructions: '1. Sit with back supported\n2. Support right arm with left hand\n3. Slowly raise right arm forward to shoulder level only\n4. Hold 2 seconds\n5. Lower slowly\n6. Repeat with left arm',
    recoveryBenefit: 'Maintains shoulder mobility without straining healing sternum, prevents frozen shoulder from immobility',
    defaultSets: 2,
    defaultReps: 5,
    defaultDuration: 3,
    isActive: true,
    formTips: 'CRITICAL: Respect sternum precautions - NO lifting arms above shoulder level in weeks 1-2. Use opposite hand to bear weight of moving arm. Move very slowly and gently. Stop immediately if you feel clicking, popping, or pain in sternum. Keep movements in front of body, not to sides. Breathe normally throughout.',
    modifications: 'Easier: Raise arm only to chest level (not shoulder), reduce to 3 reps per side, keep arm fully supported. Harder: After week 3, gradually raise to ear level, reduce support from opposite hand, add 1-2 second holds. If shoulder is very stiff, use a wand or stick between hands for bilateral support.',
  },
  {
    name: 'Shoulder Shrugs',
    description: 'Gentle shoulder elevation to relieve tension',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Sit or stand with arms at sides\n2. Raise both shoulders toward ears\n3. Hold for 3 seconds\n4. Release and relax shoulders down\n5. Feel tension release',
    recoveryBenefit: 'Relieves neck and shoulder tension from positioning during surgery, improves upper body circulation, reduces muscle guarding',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 2,
    isActive: true,
    formTips: 'Keep arms completely relaxed and hanging at sides. Lift shoulders straight up, not rolling forward or back. Feel muscles release when lowering - this is the therapeutic part. Don\'t force height - gentle elevation is sufficient. Breathe in while lifting, out while lowering. This should feel relieving, not straining.',
    modifications: 'Easier: Reduce hold to 1-2 seconds, perform 5 reps only, sit with back support. Harder: Hold for 5 seconds, add small circles at top of shrug, increase to 15 reps, perform while walking. Can add very light weights (0.5-1 lb) after week 4 if cleared.',
  },

  // ========== PHASE 2: WEEKS 3-4 - EARLY RECOVERY (Light Activity, Standing Balance) ==========

  {
    name: 'Marching in Place (Seated)',
    description: 'Gentle alternating knee lifts while sitting',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'Sturdy chair',
    minPostOpWeek: 2,
    maxPostOpWeek: 4,
    instructions: '1. Sit on edge of chair with back straight\n2. Lift right knee a few inches\n3. Lower and lift left knee\n4. Alternate slowly and controlled\n5. Breathe normally throughout',
    recoveryBenefit: 'Begins cardiovascular conditioning safely, strengthens hip flexors, improves leg strength for walking, increases heart rate gradually',
    defaultSets: 2,
    defaultReps: 20,
    defaultDuration: 3,
    isActive: true,
    formTips: 'Sit tall with core engaged. Lift knees only 4-6 inches initially - height isn\'t important. Keep movement smooth and rhythmic. Breathe continuously in rhythm with movement. Stop if heart rate becomes excessive or you feel chest discomfort. Monitor for dizziness or unusual shortness of breath.',
    modifications: 'Easier: Lift knees only 2-3 inches, reduce to 10 reps per set, rest 1-2 minutes between sets, slow pace significantly. Harder: Lift knees higher (toward chest), increase pace slightly, add arm movements (opposite arm forward), increase to 30 reps. Can be done with back fully supported initially.',
  },
  {
    name: 'Heel Slides',
    description: 'Gentle knee bending exercise while lying down',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 2,
    maxPostOpWeek: 6,
    instructions: '1. Lie on back with legs straight\n2. Slide right heel toward buttocks, bending knee\n3. Keep foot on surface\n4. Hold for 2 seconds\n5. Slide back to straight\n6. Repeat with left leg',
    recoveryBenefit: 'Strengthens quadriceps needed for walking, improves knee flexibility, builds leg strength without stressing heart',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep heel in contact with surface throughout - sliding friction makes this more effective. Don\'t force knee to bend deeply. Keep opposite leg relaxed and flat. Lower back should stay neutral, not arching. Breathe normally. Stop if knee pain occurs.',
    modifications: 'Easier: Bend knee only partway, reduce to 5-8 reps, place towel under heel to reduce friction. Harder: Increase bend to comfortable maximum, add 3-5 second hold, place resistance band around foot, increase to 15 reps. Can be done on bed or floor.',
  },
  {
    name: 'Seated Knee Extensions',
    description: 'Straightening knee while seated to strengthen quadriceps',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair',
    minPostOpWeek: 3,
    maxPostOpWeek: 6,
    instructions: '1. Sit with back supported, feet flat\n2. Slowly straighten right knee\n3. Hold leg parallel to ground for 3 seconds\n4. Lower slowly\n5. Repeat with left leg',
    recoveryBenefit: 'Builds quadriceps strength essential for walking and stairs, improves leg endurance, strengthens muscles that support heart function through movement',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Sit with back fully supported and core engaged. Lift leg smoothly, don\'t kick up. Hold leg steady at top - no bouncing. Flex foot to engage more muscle. Breathe out during extension, in during lowering. Stop if knee pain or unusual fatigue.',
    modifications: 'Easier: Lift leg only halfway, reduce hold to 1-2 seconds, perform 5-8 reps only. Harder: Add ankle weights (start with 1 lb), increase hold to 5 seconds, point and flex foot at top. Can add resistance band around ankle for added challenge after week 5.',
  },
  {
    name: 'Sit-to-Stand Practice',
    description: 'Controlled standing from seated position',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Sturdy chair',
    minPostOpWeek: 3,
    maxPostOpWeek: 6,
    instructions: '1. Sit on edge of chair, feet flat\n2. Lean forward slightly\n3. Push through legs to stand (use arms for assist if needed)\n4. Straighten to full standing\n5. Slowly lower back to sitting',
    recoveryBenefit: 'Builds functional strength for daily activities, improves leg power, increases cardiovascular demand safely, essential for independence',
    defaultSets: 2,
    defaultReps: 5,
    defaultDuration: 3,
    isActive: true,
    formTips: 'Feet should be hip-width apart and slightly behind knees. Lean forward (nose over toes) before standing. Push through heels, not toes. Use arms on chair for light assist only if needed. Lower with control - don\'t plop down. Stop if dizzy or short of breath. Monitor heart rate response.',
    modifications: 'Easier: Use chair with arms for support, elevate chair height with cushion, reduce to 3 reps only, take longer rest between reps. Harder: Eliminate arm use, use lower chair, increase to 10 reps, slow down descent phase to 4-5 seconds. Can hold light weights after week 6.',
  },
  {
    name: 'Wall Push-Ups (Modified)',
    description: 'Gentle chest and arm strengthening against wall',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Wall',
    minPostOpWeek: 4,
    maxPostOpWeek: 8,
    contraindications: 'Wait until sternum is stable, avoid if chest pain',
    instructions: '1. Stand arm\'s length from wall\n2. Place hands on wall at shoulder height\n3. Lean forward slowly, bending elbows\n4. Push back to starting position\n5. Keep body straight',
    recoveryBenefit: 'Gradually strengthens chest and arm muscles without excessive sternum stress, improves upper body function for daily tasks, builds confidence in using arms',
    defaultSets: 2,
    defaultReps: 8,
    defaultDuration: 3,
    isActive: true,
    formTips: 'IMPORTANT: Only after week 4 when sternum is stabilizing. Keep body in straight line from head to heels. Lower slowly over 2-3 seconds. Elbows should go back at 45 degrees, not straight out. Stop immediately if sternum clicking/pain. Breathe in going down, out pushing up. Start conservatively.',
    modifications: 'Easier: Stand further from wall (less angle), reduce to 5 reps, perform very shallow bend only. Harder: Step closer to wall (more angle), increase to 12 reps, add 2-second hold at bottom, slow tempo to 3-2-3 count. Progress to counter height push-ups when ready.',
  },
  {
    name: 'Standing March',
    description: 'Alternating knee lifts while standing with support',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair or counter for balance',
    minPostOpWeek: 3,
    maxPostOpWeek: 6,
    instructions: '1. Stand with hand on support for balance\n2. Lift right knee to comfortable height\n3. Lower and place foot down\n4. Lift left knee\n5. Continue alternating at comfortable pace',
    recoveryBenefit: 'Increases heart rate safely, improves balance and coordination, strengthens hip flexors, builds cardiovascular endurance',
    defaultSets: 2,
    defaultReps: 20,
    defaultDuration: 3,
    isActive: true,
    formTips: 'Use support lightly for balance only, not to hold body weight. Keep standing leg slightly bent. Lift knee only to comfortable height - hip level is not required initially. Maintain upright posture, don\'t lean back. Breathe rhythmically. Stop if excessively winded or dizzy.',
    modifications: 'Easier: Lift knees only 6 inches, slow the pace, reduce to 10 reps per set, use firm support. Harder: Lift knees to hip level, increase pace, reduce support to fingertip touch, add opposite arm reach, increase to 30 reps. Progress to no support when balance improves.',
  },

  // FLEXIBILITY - Critical for maintaining ROM
  {
    name: 'Neck Rotation Stretch',
    description: 'Gentle neck turns to relieve tension',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 2,
    maxPostOpWeek: null,
    instructions: '1. Sit with good posture\n2. Slowly turn head to look over right shoulder\n3. Hold for 10 seconds\n4. Return to center\n5. Turn to look over left shoulder\n6. Hold for 10 seconds',
    recoveryBenefit: 'Reduces neck stiffness from bed rest, improves range of motion, relieves tension from surgical positioning',
    defaultSets: 2,
    defaultReps: 5,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Move slowly and gently - neck is delicate. Turn head only as far as comfortable without forcing. Keep shoulders down and relaxed. If you feel pinching or sharp pain, reduce range. Breathe normally throughout stretch. Never bounce or jerk.',
    modifications: 'Easier: Turn head only partway, reduce hold to 5 seconds, perform 3 reps per side only. Harder: Increase hold to 15-20 seconds, add gentle pressure with hand, combine with shoulder rolls. Can be done multiple times per day for relief.',
  },
  {
    name: 'Shoulder Rolls',
    description: 'Circular shoulder movements to improve mobility',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 2,
    maxPostOpWeek: null,
    instructions: '1. Sit or stand with arms relaxed\n2. Roll shoulders forward in circular motion - 5 times\n3. Roll shoulders backward in circular motion - 5 times\n4. Move slowly and smoothly',
    recoveryBenefit: 'Prevents shoulder stiffness, improves circulation to upper body, reduces muscle tension from protective posturing',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 3,
    isActive: true,
    formTips: 'Make smooth circles with shoulders, not jerky movements. Keep arms completely relaxed. Roll through full range - up, back, down, forward. Don\'t force or rush. Breathe naturally. This should feel releasing, not effortful.',
    modifications: 'Easier: Make smaller circles, reduce to 5 reps each direction, sit with back support. Harder: Make larger circles, increase to 15 reps each direction, stand while performing, combine with arm swings. Can add alternating rolls (one shoulder at a time).',
  },
  {
    name: 'Wrist Circles',
    description: 'Rotating wrists to maintain flexibility',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Extend arms forward at shoulder height (or rest elbows on armrests)\n2. Make circles with hands at wrist\n3. 10 circles clockwise\n4. 10 circles counterclockwise',
    recoveryBenefit: 'Maintains wrist flexibility for daily activities, improves circulation to hands and arms',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 2,
    isActive: true,
    formTips: 'Make full circles with hands, not just wiggling. Keep forearms still, movement only at wrist. No pain should occur. Breathe normally. Can do this frequently throughout day, especially if hands feel stiff.',
    modifications: 'Easier: Make smaller circles, reduce to 5 reps each direction, rest elbows on armrests. Harder: Make larger circles, increase to 15 reps, add wrist flexion/extension holds, clasp hands and circle together. Can add light grip strengthening with soft ball.',
  },

  // ========== PHASE 3: WEEKS 5-6 - BUILDING ENDURANCE (Light Cardio, Basic Resistance) ==========

  {
    name: 'Slow Walking (Indoor)',
    description: 'Controlled pace walking for cardiovascular conditioning',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 3,
    maxPostOpWeek: null,
    instructions: '1. Walk at comfortable pace indoors\n2. Maintain steady breathing\n3. Start with 5 minutes\n4. Increase by 1-2 minutes per session\n5. Stop if experiencing chest pain, dizziness, or severe shortness of breath',
    recoveryBenefit: 'Cornerstone of cardiac rehabilitation - strengthens heart muscle, improves circulation, lowers blood pressure, builds endurance safely',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 10,
    isActive: true,
    videoUrl: 'https://www.youtube.com/watch?v=Zd8zDJPQhCc',
    imageUrl: 'https://i.ytimg.com/vi/Zd8zDJPQhCc/maxresdefault.jpg',
    formTips: 'Start very slowly - pace isn\'t important initially. Maintain upright posture, shoulders back. Breathe rhythmically through nose and mouth. Stay within talk test range (can speak in sentences). Use assistive device if balance is an issue. Stop immediately if chest pain, extreme shortness of breath, or dizziness.',
    modifications: 'Easier: Walk for just 3-5 minutes, take frequent breaks, use walker or cane, stay close to walls/support. Harder: Increase duration by 2 minutes per session, add gentle arm swings, include slight variations in pace. Can progress to hallway laps or around block when ready.',
  },
  {
    name: 'Treadmill Walking (Level)',
    description: 'Controlled treadmill walking at flat grade',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'Treadmill',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Start at slow speed (1.5-2 mph)\n2. Hold side rails initially if needed\n3. Maintain upright posture\n4. Progress speed gradually\n5. Monitor heart rate stays in target zone',
    recoveryBenefit: 'Controlled cardiovascular conditioning, consistent pace helps regulate heart rate, builds endurance for daily activities',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 15,
    isActive: true,
    formTips: 'Use safety clip always. Start very slow (1.0-1.5 mph initially). Hold rails lightly only if needed for balance, not to support body weight. Keep eyes forward, not down at feet. Maintain natural walking stride. Monitor heart rate stays in prescribed zone. Never jump off a moving treadmill.',
    modifications: 'Easier: Start at 0.8-1.0 mph, use rails for balance, limit to 5-10 minutes, take mid-session break. Harder: Gradually increase to 2.5-3.0 mph, release handrails, increase duration to 30 minutes, add 0.5-1% incline after week 8. Always warm up and cool down with slower pace.',
  },
  {
    name: 'Stationary Bike (Low Resistance)',
    description: 'Gentle cycling for cardiovascular fitness',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'Stationary bike',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Adjust seat to proper height\n2. Start with zero or minimal resistance\n3. Pedal at comfortable, steady pace\n4. Keep RPM between 50-60\n5. Maintain proper posture',
    recoveryBenefit: 'Low-impact cardio strengthens heart without joint stress, improves leg strength and endurance, excellent for weight management',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 15,
    isActive: true,
    videoUrl: 'https://www.youtube.com/watch?v=rLbMOiabRhE',
    imageUrl: 'https://i.ytimg.com/vi/rLbMOiabRhE/maxresdefault.jpg',
    formTips: 'Adjust seat so knee has slight bend at bottom of pedal stroke. Keep resistance very light initially. Maintain upright posture, no hunching. Pedal smoothly in circles, not pushing hard. Monitor heart rate continuously. Stop if you feel chest pain, excessive breathlessness, or leg cramping.',
    modifications: 'Easier: Start with zero resistance, pedal for just 5-10 minutes, keep RPM at 40-50, take break mid-session. Harder: Gradually add light resistance, increase to 25-30 minutes, increase RPM to 60-70, add short intervals of slightly higher resistance. Can use recumbent bike if more comfortable.',
  },
  {
    name: 'Step-Ups (Low Step)',
    description: 'Stepping up onto low platform',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: '4-6 inch step or stair',
    minPostOpWeek: 5,
    maxPostOpWeek: 8,
    instructions: '1. Face a low step\n2. Step up with right foot\n3. Bring left foot up to meet right\n4. Step down with right foot\n5. Bring left foot down\n6. Use handrail if available',
    recoveryBenefit: 'Simulates stair climbing for daily function, strengthens legs for real-world activities, increases cardiovascular demand gradually',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Use handrail for balance. Step fully onto platform with entire foot. Push through heel of stepping leg. Step down slowly and controlled - descent is harder on heart. Breathe continuously, exhale during step up. Stop if knee pain or excessive breathlessness. Start with very low step (4 inches).',
    modifications: 'Easier: Use 2-3 inch step, hold rail firmly, reduce to 5 reps, rest longer between sets. Harder: Progress to 6-8 inch step, reduce rail support, increase to 15 reps, alternate leading leg each rep. Can add light handheld weights after week 8.',
  },
  {
    name: 'Standing Hip Abduction',
    description: 'Leg lifts to the side for hip strength',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair for balance',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Stand with hand on chair for support\n2. Keep standing leg slightly bent\n3. Lift right leg out to side, keeping toe forward\n4. Lift only to comfortable height\n5. Lower slowly\n6. Repeat then switch legs',
    recoveryBenefit: 'Strengthens hip stabilizers for balance and walking, improves lateral stability, prevents falls',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Stand tall with core engaged. Keep standing leg slightly bent. Lift leg directly to side, don\'t lean or shift weight. Toe should point forward, not up. Control the lowering - don\'t let leg drop. Keep hips level, don\'t hike hip. Breathe normally.',
    modifications: 'Easier: Lift leg only 6 inches, hold chair firmly, reduce to 8 reps, rest between sides. Harder: Lift leg higher (not above hip), hold at top for 2 seconds, reduce chair support, add ankle weights (1-2 lbs). Can add resistance band around ankles.',
  },
  {
    name: 'Standing Hip Extension',
    description: 'Backward leg lifts for glute strength',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair for balance',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Stand facing chair, hands on back for support\n2. Keep standing leg slightly bent\n3. Extend right leg straight back\n4. Squeeze glutes\n5. Hold 2 seconds\n6. Lower and repeat, then switch',
    recoveryBenefit: 'Strengthens glutes and hamstrings crucial for walking and standing, improves posterior chain strength, supports lower back',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep torso upright, don\'t lean forward. Squeeze glutes to lift leg back. Keep knee straight but not locked. Don\'t arch lower back excessively. Control the movement - no swinging. Standing leg slightly bent. Stop if lower back pain occurs.',
    modifications: 'Easier: Lift leg only 6-8 inches back, hold chair firmly, reduce to 8 reps. Harder: Lift leg higher, hold for 3 seconds, use fingertip support only, add ankle weights. Can progress to resistance band around ankles for more challenge.',
  },
  {
    name: 'Seated Row (Resistance Band)',
    description: 'Pulling motion with elastic band for back strength',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Resistance band',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Sit with legs extended, band around feet\n2. Hold ends of band in each hand\n3. Sit upright with shoulders back\n4. Pull band toward body, squeezing shoulder blades\n5. Return slowly to start',
    recoveryBenefit: 'Strengthens upper back to improve posture post-surgery, counteracts forward shoulder position, builds functional pulling strength',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Sit tall with core engaged throughout. Pull shoulder blades together, not just bending elbows. Keep elbows close to body. Return with control, don\'t let band snap back. Exhale during pull, inhale during release. Stop if sternum discomfort - this engages chest muscles indirectly.',
    modifications: 'Easier: Use lighter resistance band, reduce to 8 reps, perform single arm rows. Harder: Use stronger band, increase to 15 reps, add 2-second hold at chest, slow tempo to 2-2-2. Can perform standing if preferred after week 8.',
  },
  {
    name: 'Bicep Curls (Light Weight)',
    description: 'Arm curls with 1-2 lb weights',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: '1-2 lb dumbbells or cans',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Stand or sit with weights in hands\n2. Arms at sides, palms forward\n3. Bend elbows, curl weights to shoulders\n4. Keep elbows at sides\n5. Lower slowly to start',
    recoveryBenefit: 'Builds arm strength for daily tasks like carrying groceries, maintains upper body function, improves confidence in arm use',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep elbows stationary at sides, don\'t swing them. Curl weight with smooth motion, no jerking. Control the lowering phase (2-3 seconds down). Keep wrists straight, don\'t bend them. Exhale during curl, inhale during lower. Core engaged, don\'t arch back.',
    modifications: 'Easier: Use 0.5-1 lb weights or no weight, reduce to 8 reps, perform seated. Harder: Increase to 3-5 lbs, increase to 15 reps, alternate arms, add pause at top. Can progress to hammer curls or concentration curls for variety.',
  },

  // ========== PHASE 4: WEEKS 7-8 - MODERATE INTENSITY (Increased Duration and Resistance) ==========

  {
    name: 'Brisk Walking',
    description: 'Faster-paced walking for cardiovascular fitness',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Walk at pace where you can talk but not sing\n2. Swing arms naturally\n3. Maintain good posture\n4. Breathe rhythmically\n5. Aim for 20-30 minutes',
    recoveryBenefit: 'Significantly improves cardiovascular fitness, strengthens heart muscle, reduces risk of future cardiac events, helps control weight and blood pressure',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 25,
    isActive: true,
    formTips: 'Walk fast enough to elevate heart rate but can still talk. Swing arms naturally at sides. Land heel first, roll through foot. Take deep breaths rhythmically. Use talk test - can speak sentences but not sing. Monitor for unusual shortness of breath, chest discomfort, or extreme fatigue.',
    modifications: 'Easier: Reduce pace slightly, shorten duration to 15-20 minutes, take 2-minute slow-down breaks. Harder: Increase pace gradually, extend to 40-45 minutes, add hills or stairs, use walking poles for upper body engagement. Track distance and try to gradually increase.',
  },
  {
    name: 'Incline Walking (Treadmill)',
    description: 'Walking on slight incline for increased intensity',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Treadmill',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Start at 0% incline, warm up 5 min\n2. Gradually increase incline to 2-3%\n3. Maintain steady pace\n4. Monitor heart rate and breathing\n5. Decrease incline if becomes too difficult',
    recoveryBenefit: 'Increases cardiovascular demand safely, builds leg strength, simulates outdoor walking conditions, improves exercise capacity',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 20,
    isActive: true,
    formTips: 'Don\'t hold rails tightly - light fingertip touch only if needed. Lean slightly into incline but stay upright. Shorten stride on incline. Breathe deeply and rhythmically. Monitor heart rate closely - incline increases demand significantly. Start with minimal incline (0.5-1%).',
    modifications: 'Easier: Start at 0.5% incline only, reduce speed, limit to 10-15 minutes, alternate flat and incline minutes. Harder: Gradually increase to 3-5% incline, maintain speed, extend duration, reduce handrail use. Always include 5-minute flat warm-up and cool-down.',
  },
  {
    name: 'Stationary Bike (Moderate Resistance)',
    description: 'Cycling with increased resistance',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Stationary bike',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Warm up 5 minutes at low resistance\n2. Increase to moderate resistance level\n3. Maintain RPM 60-70\n4. Cycle for 20-25 minutes\n5. Cool down 5 minutes at low resistance',
    recoveryBenefit: 'Builds cardiovascular endurance, strengthens legs without joint impact, excellent calorie burning for weight management',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 25,
    isActive: true,
    formTips: 'Resistance should allow you to pedal smoothly. If you\'re grinding or bouncing in seat, reduce resistance. Keep shoulders relaxed. Maintain conversation-level breathing. Check heart rate every 5 minutes. If you feel excessive leg fatigue or breathlessness, reduce resistance immediately.',
    modifications: 'Easier: Use light resistance only, reduce to 15-20 minutes, keep RPM at 50-60, take mid-session break. Harder: Gradually increase resistance, extend to 35-40 minutes, increase RPM to 70-80, add interval training (vary resistance). Can try standing briefly on pedals if comfortable.',
  },
  {
    name: 'Elliptical Training',
    description: 'Low-impact cardio machine using arms and legs',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Elliptical machine',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Start with low resistance\n2. Use both arm handles and leg pedals\n3. Maintain upright posture\n4. Smooth, controlled movements\n5. Build up duration gradually',
    recoveryBenefit: 'Full-body cardio workout, low impact on joints, engages both upper and lower body, excellent for endurance building',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 20,
    isActive: true,
    formTips: 'Keep feet flat on pedals throughout. Use both arms and legs equally. Stand upright, don\'t lean heavily on handles. Move smoothly - elliptical should be nearly silent. Start with very low resistance. Monitor heart rate constantly. Stop if you feel unsteady or overly fatigued.',
    modifications: 'Easier: Use zero resistance, move slowly, focus on forward direction only, limit to 10 minutes. Harder: Add light resistance, increase speed, try reverse direction, extend to 30 minutes, use arms more actively. Can also use without holding handles for better balance challenge.',
  },
  {
    name: 'Mini Squats',
    description: 'Quarter squats for leg strength',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Chair for support',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Stand with feet shoulder-width apart\n2. Hold chair for balance if needed\n3. Bend knees and hips slightly (quarter squat)\n4. Keep chest up and weight in heels\n5. Return to standing',
    recoveryBenefit: 'Strengthens major leg muscles (quads, glutes, hamstrings) essential for daily activities, improves functional strength, builds bone density',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Feet shoulder-width, toes slightly out. Squat only 1/4 depth initially (knees bend just slightly). Keep weight in heels, not toes. Chest up, look forward. Don\'t let knees cave inward. Breathe in going down, out standing up. Use chair for safety backup.',
    modifications: 'Easier: Hold chair throughout, squat just a few inches, reduce to 8 reps, widen stance. Harder: Reduce chair support, squat to 1/2 depth, increase to 15 reps, hold for 2 seconds at bottom. Can add light weight held at chest after week 9.',
  },
  {
    name: 'Standing Calf Raises',
    description: 'Rising on toes to strengthen calves',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Chair or wall for balance',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Stand with feet hip-width apart\n2. Hold support for balance\n3. Rise up on toes as high as comfortable\n4. Hold for 2 seconds\n5. Lower heels to floor slowly',
    recoveryBenefit: 'Strengthens calves for walking and balance, improves circulation from legs back to heart (calf muscle pump), prevents ankle weakness',
    defaultSets: 2,
    defaultReps: 15,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Rise up smoothly on balls of feet. Hold balance at top. Lower heels below starting point if possible (stretch). Keep core engaged. Don\'t bounce. Use support for balance only. Breathe normally throughout. Stop if calf cramping.',
    modifications: 'Easier: Hold support firmly, rise only partway, reduce to 10 reps, rest between sets. Harder: Use fingertip support only, hold at top 3-4 seconds, increase to 20 reps, try single-leg raises. Can add weight by holding dumbbells after week 9.',
  },
  {
    name: 'Lat Pulldown (Light Weight)',
    description: 'Overhead pulling motion with cable or band',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Resistance band or cable machine',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Sit with band secured overhead or use machine\n2. Grasp handles with arms extended\n3. Pull down to chest level\n4. Squeeze shoulder blades together\n5. Return slowly to start',
    recoveryBenefit: 'Strengthens lat muscles important for upper body function, improves pulling strength for daily tasks, builds back strength',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Sit with thighs secured under pad. Pull bar down to upper chest, not behind neck. Lean back slightly (10-15 degrees). Squeeze shoulder blades down and together. Control the return - don\'t let weight stack slam. Exhale during pull, inhale during release.',
    modifications: 'Easier: Use minimal weight, perform partial range, reduce to 8 reps, take longer rest. Harder: Increase weight gradually, pull to chest, increase to 15 reps, vary grip width. Can substitute resistance band pulldowns if no machine available.',
  },
  {
    name: 'Overhead Press (Light Weight)',
    description: 'Pressing light weights overhead',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: '2-5 lb dumbbells',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    contraindications: 'Only after full sternum healing, avoid if shoulder pain',
    instructions: '1. Stand or sit with weights at shoulder level\n2. Press weights overhead until arms extended\n3. Keep core engaged\n4. Lower slowly to shoulders\n5. Breathe out on press up',
    recoveryBenefit: 'Builds shoulder strength for overhead activities (reaching shelves, etc.), strengthens deltoids and triceps, improves functional upper body capacity',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'IMPORTANT: Only after 8+ weeks and complete sternum healing. Press straight up, not forward. Keep core tight, don\'t arch back. Lower weights to shoulder level with control. Breathe out during press, in during lowering. Stop immediately if any sternum discomfort.',
    modifications: 'Easier: Use 1-2 lbs only, perform seated with back support, reduce to 6-8 reps, press to partial height. Harder: Increase to 8-10 lbs, perform standing, increase to 12 reps, add pause at top. Can alternate arms for added control.',
  },
  {
    name: 'Chest Fly (Light Weight)',
    description: 'Opening arms with light weights for chest',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: '2-3 lb dumbbells',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    contraindications: 'Only after complete sternum healing (8+ weeks), stop if chest discomfort',
    instructions: '1. Lie on bench or floor, knees bent\n2. Hold light weights above chest, arms slightly bent\n3. Open arms out to sides in arc motion\n4. Feel chest stretch\n5. Bring back to start',
    recoveryBenefit: 'Carefully strengthens chest muscles after sternum healing, improves chest flexibility, builds confidence in using chest muscles',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'CRITICAL: Only after complete sternum healing (8+ weeks minimum). Keep slight bend in elbows throughout. Open arms only to comfortable stretch, not beyond shoulder line. Move slowly and controlled. Stop immediately if any chest clicking or pain. Start with very light weight (2-3 lbs max).',
    modifications: 'Easier: Use 1-2 lbs only, reduce arm opening range, perform 6-8 reps only, keep arms higher (less stretch). Harder: Increase to 4-5 lbs, full comfortable range, increase to 12 reps, slow tempo. Can substitute resistance band chest fly.',
  },

  // CORE STRENGTHENING - Important but must be gentle
  {
    name: 'Abdominal Bracing',
    description: 'Isometric core engagement',
    category: 'core',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Lie on back with knees bent\n2. Tighten abdominal muscles (as if bracing for punch)\n3. Hold for 5-10 seconds while breathing normally\n4. Do not hold breath\n5. Relax and repeat',
    recoveryBenefit: 'Activates core muscles without stressing sternum, improves core stability for daily movements, supports back health',
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Tighten abs as if bracing for a punch - firm but not maximum clench. Keep breathing normally - don\'t hold breath. Back stays in neutral position. Feel all abdominal muscles engage. This is isometric (no movement). Stop if this causes back pain.',
    modifications: 'Easier: Hold for just 3-5 seconds, reduce to 5 reps, practice while lying down. Harder: Hold for 10-15 seconds, increase to 15 reps, perform while sitting or standing, add limb movements while bracing. Can progress to dead bug exercise.',
  },
  {
    name: 'Pelvic Tilts',
    description: 'Gentle lower back and core activation',
    category: 'core',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Lie on back, knees bent, feet flat\n2. Flatten lower back against floor by tilting pelvis\n3. Engage core muscles\n4. Hold for 5 seconds\n5. Release and repeat',
    recoveryBenefit: 'Strengthens core without crunches, protects lower back, improves posture, safe for healing sternum',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Press lower back flat against floor using core, not leg push. Think of tilting pelvis up toward ceiling. Keep shoulders and upper back relaxed on floor. Breathe normally throughout. Should feel gentle core engagement, not straining.',
    modifications: 'Easier: Tilt only partially, hold 2-3 seconds, reduce to 8 reps. Harder: Hold 8-10 seconds, increase to 15 reps, add simultaneous arm raise, lift one leg while holding tilt. Can progress to bridges when ready.',
  },
  {
    name: 'Bird Dog (Modified)',
    description: 'Alternating arm and leg extensions on hands and knees',
    category: 'core',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Start on hands and knees\n2. Extend right arm forward while extending left leg back\n3. Keep back flat and core engaged\n4. Hold 5 seconds\n5. Return and switch sides',
    recoveryBenefit: 'Improves balance and core stability, strengthens back muscles, enhances coordination, functional strength',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep back flat throughout - no sagging or arching. Extend limbs only to comfortable height. Move slowly and controlled. Balance is key, not height. Keep hips level. Breathe normally. Stop if wrist or knee pain. Can use padding under knees.',
    modifications: 'Easier: Lift only arm or only leg (not both), reduce range, hold 2-3 seconds, reduce to 6 reps. Harder: Extend limbs fully, hold 8-10 seconds, increase to 15 reps, draw knee to elbow between reps. Can add ankle/wrist weights for challenge.',
  },
  {
    name: 'Standing Core Rotation',
    description: 'Twisting motion to engage obliques',
    category: 'core',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Stand with feet shoulder-width\n2. Hold hands at chest level\n3. Rotate torso to right, keeping hips forward\n4. Return to center\n5. Rotate to left',
    recoveryBenefit: 'Strengthens oblique muscles for rotation movements, improves flexibility for daily activities like reaching, looking behind while driving',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep hips and legs stationary, rotation only through torso. Turn as far as comfortable without forcing. Move smoothly, no jerking. Keep core engaged throughout. Breathe naturally. Should feel gentle stretch in obliques and back.',
    modifications: 'Easier: Rotate only partway, reduce to 8 reps each side, sit if balance is issue. Harder: Hold light weight at chest, increase rotation range, hold 2 seconds at end range, increase to 15 reps. Can add resistance band for more challenge.',
  },

  // ========== PHASE 5: WEEKS 9-10 - PROGRESSIVE TRAINING (Higher Intensity Options) ==========

  {
    name: 'Interval Walking',
    description: 'Alternating between normal and brisk pace',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Warm up 5 minutes normal pace\n2. Walk briskly 2 minutes\n3. Walk normal pace 3 minutes\n4. Repeat pattern 4-5 times\n5. Cool down 5 minutes',
    recoveryBenefit: 'Increases cardiovascular fitness faster than steady pace, improves heart\'s ability to handle varying demands, burns more calories',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 30,
    isActive: true,
    formTips: 'Warm up thoroughly before intervals. Brisk pace should still allow talking but breathlessly. Normal pace should be recovery - true slow-down. Monitor heart rate during brisk intervals - stay in prescribed zone. Stop if chest discomfort or extreme breathlessness. Cool down fully.',
    modifications: 'Easier: Shorten brisk intervals to 1 minute, extend recovery to 4-5 minutes, reduce total duration to 20 minutes. Harder: Extend brisk intervals to 3-5 minutes, reduce recovery to 2 minutes, increase total duration to 40 minutes, add slight inclines. Track and gradually improve work:rest ratio.',
  },
  {
    name: 'Stair Climbing',
    description: 'Climbing actual stairs at controlled pace',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Staircase with handrail',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Use handrail for safety\n2. Climb one flight at comfortable pace\n3. Rest at top if needed\n4. Walk down slowly\n5. Repeat for 10-15 minutes total',
    recoveryBenefit: 'Excellent for cardiovascular fitness, builds leg strength, functional exercise for daily life, tests exercise capacity',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 15,
    isActive: true,
    formTips: 'Always use handrail for safety. Take one step at a time. Push through whole foot, not just toes. Breathe continuously - exhale during climb. Go down slowly - descent requires control. Take breaks as needed. Stop if excessive breathlessness or leg fatigue.',
    modifications: 'Easier: Climb just half flight, rest fully between climbs, hold rail firmly, limit to 5-10 minutes total. Harder: Climb multiple flights, reduce rest time, lighten rail use, increase total time to 20 minutes, carry light load (backpack with water). Never rush on stairs.',
  },
  {
    name: 'Rowing Machine',
    description: 'Full-body cardio using rowing ergometer',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Rowing machine',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Sit with feet secured, knees bent\n2. Grasp handle with both hands\n3. Push with legs, then pull handle to chest\n4. Extend arms, bend knees, slide forward\n5. Maintain smooth rhythm',
    recoveryBenefit: 'Low-impact full-body workout, engages 85% of body\'s muscles, excellent cardio and strength combination, builds endurance',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 20,
    isActive: true,
    formTips: 'Sequence: legs push, then lean back, then pull arms. Return: extend arms, lean forward, bend legs. Keep back straight throughout. Don\'t hunch shoulders. Start with very light resistance. Monitor heart rate closely. Stop if lower back pain develops.',
    modifications: 'Easier: Use minimal resistance, limit to 10 minutes, slow stroke rate (15-18 strokes/min), take mid-session break. Harder: Increase resistance, extend to 25-30 minutes, increase rate to 20-24 strokes/min, add intervals. Ensure proper form before increasing intensity.',
  },
  {
    name: 'Lunges (Supported)',
    description: 'Forward stepping lunge with chair support',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Chair or wall for balance',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Stand with chair to side for support\n2. Step forward with right leg\n3. Lower body until front thigh parallel to ground\n4. Back knee hovers above floor\n5. Push back to start\n6. Switch legs',
    recoveryBenefit: 'Builds functional leg strength for stairs and walking, improves balance and coordination, strengthens glutes and quads independently',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep torso upright throughout. Front knee stays behind toes. Lower straight down, not forward. Back knee hovers just above floor. Push through front heel to stand. Use support for balance only. Stop if knee pain. Start with short range.',
    modifications: 'Easier: Use firm support, perform partial depth, reduce to 6 reps per leg, step forward shorter distance. Harder: Reduce support, increase depth, increase to 12 reps, hold 2 seconds at bottom, try walking lunges. Can add light weights.',
  },
  {
    name: 'Leg Press (Light Weight)',
    description: 'Pushing weight with legs on machine',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Leg press machine',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Sit with back supported, feet on platform\n2. Push platform away by extending legs\n3. Do not lock knees\n4. Lower platform slowly with control\n5. Keep back flat on pad',
    recoveryBenefit: 'Safely builds major leg muscle groups, supports weight without loading spine, improves lower body strength for activities',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep lower back flat against pad throughout. Place feet hip to shoulder width apart. Push through heels, not toes. Don\'t lock knees at top. Control the weight down - don\'t let it drop. Breathe out during push, in during lowering.',
    modifications: 'Easier: Use minimal weight, reduce range (stop at 90 degrees), reduce to 8 reps, take longer rest. Harder: Gradually increase weight, increase range slightly, increase to 15 reps, slow tempo (3 seconds each way). Can vary foot position for different muscle emphasis.',
  },
  {
    name: 'Push-Ups (Incline)',
    description: 'Push-ups with hands elevated on bench',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Bench or sturdy surface',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    contraindications: 'Only with full sternum healing and no pain',
    instructions: '1. Place hands on bench shoulder-width apart\n2. Extend legs behind with straight body\n3. Lower chest to bench\n4. Push back up to start\n5. Keep core engaged throughout',
    recoveryBenefit: 'Progressively builds chest, shoulder, and arm strength, functional pushing motion for daily tasks, boosts upper body confidence',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'IMPORTANT: Only after 10+ weeks and complete sternum healing. Body forms straight line. Lower chest toward bench, not hips. Elbows at 45-degree angle. Lower slowly (2-3 seconds). Full arm extension at top. Stop immediately if sternum discomfort.',
    modifications: 'Easier: Use higher incline (counter height), reduce to 5-6 reps, perform on knees, reduce range. Harder: Lower incline (lower bench), increase to 15 reps, add pause at bottom, slow tempo. Eventually progress to floor push-ups.',
  },
  {
    name: 'Dumbbell Chest Press',
    description: 'Pressing weights from chest',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: '5-10 lb dumbbells',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    contraindications: 'Sternum must be completely healed',
    instructions: '1. Lie on bench with weights at chest\n2. Feet flat on floor\n3. Press weights up until arms extended\n4. Lower slowly to chest level\n5. Breathe out on press',
    recoveryBenefit: 'Rebuilds chest strength after surgery, improves pressing function for daily tasks, builds upper body power',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'CRITICAL: Sternum must be completely healed (10+ weeks). Keep feet flat on floor. Lower weights slowly and controlled. Press straight up, not angled. Keep core engaged. Stop immediately if any sternum clicking, pain, or instability. Start very light.',
    modifications: 'Easier: Use 3-5 lbs only, reduce range, perform 6-8 reps, keep elbows higher (less stretch). Harder: Increase to 10-15 lbs, full range, increase to 12 reps, vary tempo, alternate arms. Can perform on stability ball for core challenge.',
  },
  {
    name: 'Tricep Dips (Supported)',
    description: 'Using chair to work back of arms',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Sturdy chair',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Sit on edge of chair, hands beside hips\n2. Slide hips forward off chair\n3. Lower body by bending elbows\n4. Lower only a few inches initially\n5. Push back up to start',
    recoveryBenefit: 'Strengthens triceps for pushing and lifting, improves arm strength for getting up from chairs, builds functional upper body power',
    defaultSets: 2,
    defaultReps: 8,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep shoulders down and back. Lower only a few inches initially. Keep elbows pointing straight back. Core engaged to keep body straight. Push through heels of hands. Stop if shoulder discomfort. This is an advanced exercise.',
    modifications: 'Easier: Bend knees with feet closer, lower only 2-3 inches, reduce to 5 reps, use very stable chair. Harder: Extend legs fully, increase depth, increase to 12 reps, elevate feet on another chair. Can add weight on lap when very strong.',
  },

  // BALANCE TRAINING - Fall prevention
  {
    name: 'Single Leg Stance',
    description: 'Standing on one leg for balance',
    category: 'balance',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair or wall nearby',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Stand near support\n2. Lift right foot a few inches off ground\n3. Balance on left leg for 10-30 seconds\n4. Lower and repeat on other leg\n5. Touch support only if losing balance',
    recoveryBenefit: 'Prevents falls which are dangerous after surgery, improves proprioception, strengthens ankle stabilizers, boosts confidence',
    defaultSets: 3,
    defaultReps: 5,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Start with support nearby but try not to use it. Keep core engaged. Focus eyes on fixed point ahead. Distribute weight evenly on standing foot. Keep shoulders and hips level. Breathe normally. Balance improves with practice.',
    modifications: 'Easier: Hold support lightly, balance for just 5-10 seconds, perform near wall. Harder: Remove support completely, increase time to 45-60 seconds, close eyes briefly, stand on unstable surface (pillow). Can add arm movements.',
  },
  {
    name: 'Heel-to-Toe Walk',
    description: 'Tandem walking for balance',
    category: 'balance',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Walk in straight line\n2. Place heel of front foot directly against toes of back foot\n3. Walk 10-20 steps\n4. Use wall or counter if needed for balance\n5. Focus on point ahead',
    recoveryBenefit: 'Challenges balance system, improves coordination, strengthens core stabilizers, reduces fall risk',
    defaultSets: 3,
    defaultReps: 1,
    defaultDuration: 3,
    isActive: true,
    formTips: 'Walk slowly and deliberately. Keep support nearby but try not to use. Look ahead, not down at feet. Each step should have heel directly against other toes. Arms out to sides for balance if needed. This is challenging - be patient.',
    modifications: 'Easier: Allow small gap between heel and toe, use wall for fingertip support, walk only 5-10 steps. Harder: Walk 20-30 steps, remove support, walk backwards heel-to-toe, walk on line drawn on floor. Can progress to walking on foam.',
  },
  {
    name: 'Standing Knee Raises (Balance)',
    description: 'Lifting knee while balancing',
    category: 'balance',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Stand without support (or light fingertip touch)\n2. Lift right knee to hip level\n3. Hold for 5 seconds\n4. Lower slowly\n5. Repeat with left leg',
    recoveryBenefit: 'Dynamic balance training, improves stability during movement like walking, strengthens hip flexors and standing leg',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Use support nearby but try to balance independently. Keep standing leg slightly bent. Lift knee smoothly, don\'t jerk up. Hold steady at top - this is the balance challenge. Keep hips level. Core engaged throughout.',
    modifications: 'Easier: Use light fingertip support, lift knee lower, hold only 2-3 seconds, reduce to 6 reps. Harder: No support, lift knee to hip level, hold 8-10 seconds, increase to 15 reps, close eyes briefly. Can add resistance band for strength.',
  },
  {
    name: 'Side Leg Raises (Balance Challenge)',
    description: 'Lifting leg to side without support',
    category: 'balance',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Stand without holding support\n2. Lift right leg out to side\n3. Hold for 3 seconds\n4. Lower slowly\n5. Maintain upright posture throughout\n6. Switch legs',
    recoveryBenefit: 'Challenges lateral stability, strengthens hip abductors critical for walking, improves balance confidence',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Stand tall without support. Lift leg directly to side - don\'t lean opposite way. Keep toe pointing forward. Control the lowering. Core and glutes engaged. Small range is fine initially. This is difficult - don\'t get discouraged.',
    modifications: 'Easier: Use light support, lift leg only 6 inches, hold 1-2 seconds, reduce to 6 reps per side. Harder: No support, increase height, hold 5 seconds, increase to 15 reps, perform on unstable surface. Can add ankle weights.',
  },

  // ADVANCED FLEXIBILITY
  {
    name: 'Cat-Cow Stretch',
    description: 'Spinal mobility on hands and knees',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 7,
    maxPostOpWeek: null,
    instructions: '1. Start on hands and knees\n2. Arch back up like cat, chin to chest\n3. Hold 5 seconds\n4. Let belly drop, lift chin (cow)\n5. Hold 5 seconds\n6. Flow between positions',
    recoveryBenefit: 'Improves spinal flexibility, relieves back tension, gentle core activation, improves posture',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Move slowly through positions. Arch (cat) and extension (cow) should be gentle, not extreme. Coordinate with breath - exhale in cat, inhale in cow. Keep movements smooth and flowing. Use padding under knees if needed. Stop if back pain.',
    modifications: 'Easier: Reduce range of motion, move very slowly, reduce to 5-8 reps. Harder: Hold each position longer, increase to 15 reps, add side bends, coordinate with arm movements. Can perform seated on chair if floor is difficult.',
  },
  {
    name: 'Hamstring Stretch (Seated)',
    description: 'Stretching back of thigh',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Sit on edge of chair\n2. Extend right leg straight, heel on floor\n3. Keep left foot flat\n4. Lean forward from hips until stretch in back of right thigh\n5. Hold 20-30 seconds\n6. Switch legs',
    recoveryBenefit: 'Relieves tight hamstrings from sitting, improves flexibility for bending and walking, reduces lower back strain',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep back straight, don\'t round spine. Lean from hips, not waist. You should feel stretch in back of thigh, not lower back. Don\'t bounce. Breathe deeply into stretch. Only stretch to point of mild tension, never pain.',
    modifications: 'Easier: Keep knee slightly bent, lean forward less, hold only 10-15 seconds, use strap around foot. Harder: Straighten leg more, increase forward lean, hold 30-45 seconds, flex foot toward body. Can perform lying down instead.',
  },
  {
    name: 'Quadriceps Stretch (Standing)',
    description: 'Stretching front of thigh',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair or wall for balance',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Stand with support nearby\n2. Bend right knee, bringing heel toward buttocks\n3. Grasp right ankle with right hand\n4. Keep knees together\n5. Feel stretch in front of thigh\n6. Hold 20-30 seconds',
    recoveryBenefit: 'Stretches major thigh muscle often tight from sitting and exercise, improves knee flexibility, reduces muscle imbalances',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Stand tall, don\'t lean forward. Keep knees together. Pull heel gently toward buttocks - don\'t force. Should feel stretch in front of thigh. Keep core engaged. Use support for balance. Stop if knee pain.',
    modifications: 'Easier: Hold support firmly, bend knee less, hold 10-15 seconds, use strap around ankle if can\'t reach. Harder: Release support, increase knee bend, hold 30-45 seconds, pull heel closer. Can perform lying on side.',
  },
  {
    name: 'Hip Flexor Stretch',
    description: 'Stretching front of hip',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Kneel on right knee, left foot forward (lunge position)\n2. Keep torso upright\n3. Shift weight forward\n4. Feel stretch in front of right hip\n5. Hold 20-30 seconds\n6. Switch legs',
    recoveryBenefit: 'Relieves tight hip flexors from sitting, improves posture, reduces lower back strain, enhances walking mechanics',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep torso upright and core engaged. Shift weight forward from hips, not by leaning. Back knee should be cushioned. Should feel stretch in front of back hip, not back. Don\'t overarch lower back. Breathe deeply into stretch.',
    modifications: 'Easier: Use more padding under knee, reduce forward shift, hold 15 seconds, keep hands on floor for support. Harder: Lift back arm overhead, increase forward shift, hold 30-45 seconds, add rotation. Can perform standing lunge stretch against wall.',
  },
  {
    name: 'Calf Stretch (Wall)',
    description: 'Stretching calf muscles against wall',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'Wall',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Face wall, hands on wall at shoulder height\n2. Step right foot back, keep leg straight\n3. Keep heel on ground\n4. Bend left knee, lean toward wall\n5. Feel stretch in right calf\n6. Hold 20-30 seconds',
    recoveryBenefit: 'Prevents calf tightness from walking exercise, improves ankle flexibility, reduces risk of Achilles tendon issues',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep back heel down firmly - crucial for stretch. Back leg straight with slight knee bend. Front knee bends to shift weight forward. Should feel stretch in calf, not Achilles tendon. Keep toes pointing straight ahead. Don\'t bounce.',
    modifications: 'Easier: Stand closer to wall, reduce forward lean, hold 15 seconds, keep back knee slightly bent. Harder: Step further back, increase forward lean, hold 30-45 seconds, straighten back knee more. Can also stretch with knee bent for soleus muscle.',
  },
  {
    name: 'Chest Doorway Stretch',
    description: 'Opening chest muscles in doorway',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'Doorway',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    contraindications: 'Only after complete sternum healing, be very gentle',
    instructions: '1. Stand in doorway\n2. Place forearms on door frame at shoulder height\n3. Step forward with one foot\n4. Feel gentle stretch across chest\n5. Do not overstretch\n6. Hold 20 seconds',
    recoveryBenefit: 'Gently stretches chest muscles that may be tight from surgery and protective posturing, improves posture, opens breathing',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
    formTips: 'IMPORTANT: Only after complete sternum healing (8+ weeks). Start very gentle. Place forearms on frame at shoulder height. Step forward slightly - should feel mild stretch across chest. Never force. Stop immediately if any sternum discomfort. Breathe deeply.',
    modifications: 'Easier: Very light stretch only, hold 10-15 seconds, place arms higher (less stretch), step forward less. Harder: Increase forward step, lower arms slightly (more stretch), hold 30 seconds, vary arm height. Can perform with resistance band.',
  },
  {
    name: 'Upper Back Stretch',
    description: 'Stretching between shoulder blades',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Sit or stand\n2. Clasp hands in front at chest level\n3. Push hands forward, rounding upper back\n4. Let chin drop toward chest\n5. Feel stretch between shoulder blades\n6. Hold 20 seconds',
    recoveryBenefit: 'Relieves upper back tension, counteracts forward shoulder posture, improves thoracic spine mobility',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Round upper back like making a C-shape. Push hands forward to separate shoulder blades. Let head drop naturally. Should feel stretch between shoulder blades. Don\'t force - gentle stretch only. Breathe deeply into back.',
    modifications: 'Easier: Reduce rounding, hold 10 seconds, perform while seated with back support. Harder: Increase rounding, hold 25-30 seconds, pull hands further apart, add gentle side-to-side movement. Can perform standing.',
  },

  // ========== PHASE 6: WEEKS 11-12 - FINAL PHASE (Independence, Lifelong Habits) ==========

  {
    name: 'Outdoor Walking',
    description: 'Walking outside on varied terrain',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Choose safe route with sidewalks\n2. Walk at brisk pace for 30-45 minutes\n3. Include some hills if able\n4. Maintain proper posture\n5. Monitor for any symptoms',
    recoveryBenefit: 'Real-world cardiovascular conditioning, varied terrain challenges balance and strength, sunshine and fresh air benefit mood and vitamin D',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 35,
    isActive: true,
    formTips: 'Choose safe, flat routes initially. Wear proper walking shoes. Carry phone for safety. Walk during daylight in well-populated areas. Be aware of weather - avoid extreme heat/cold initially. Start on familiar routes. Monitor how you feel continuously.',
    modifications: 'Easier: Walk 20-25 minutes, choose completely flat route, walk with partner, stay close to home. Harder: Extend to 45-60 minutes, include gentle hills, increase pace, try different terrains. Always tell someone your route and expected return time.',
  },
  {
    name: 'Swimming (Easy Pace)',
    description: 'Swimming laps at comfortable pace',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Pool access',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    contraindications: 'Sternum incision must be completely healed and cleared by surgeon',
    instructions: '1. Swim laps at easy pace\n2. Use freestyle, backstroke, or any comfortable stroke\n3. Rest between laps as needed\n4. Start with 10-15 minutes\n5. Build up gradually',
    recoveryBenefit: 'Excellent low-impact full-body cardio, water supports body weight, works all major muscle groups, very safe for joints',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 20,
    isActive: true,
    videoUrl: 'https://www.youtube.com/watch?v=5HLW2AI1Ink',
    imageUrl: 'https://i.ytimg.com/vi/5HLW2AI1Ink/maxresdefault.jpg',
    formTips: 'IMPORTANT: Incision must be completely healed and approved by surgeon. Start in shallow end. Use gentle strokes only. Freestyle and backstroke are easiest. Take frequent breaks at pool edge. Stop if you feel overly fatigued. Never swim alone.',
    modifications: 'Easier: Walk in water instead, use pool buoy for leg support, swim just 5-10 minutes, rest after each lap. Harder: Increase duration to 30 minutes, reduce rest between laps, try different strokes, add water aerobics moves. Always have lifeguard or companion present.',
  },
  {
    name: 'Water Aerobics',
    description: 'Group exercise class in pool',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Pool access',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    contraindications: 'Full healing of all incisions required',
    instructions: '1. Join a water aerobics class\n2. Follow instructor for movements\n3. Work at your own pace\n4. Water provides resistance and support\n5. Typically 45-60 minute classes',
    recoveryBenefit: 'Social exercise environment, low-impact full-body workout, water resistance builds strength, fun and motivating',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 45,
    isActive: true,
    formTips: 'Tell instructor about cardiac history. Work at your own pace regardless of class. Water should be chest deep for most moves. Move through water resistance, don\'t fight it. Stay hydrated despite being in water. Never overexert - modify any exercise.',
    modifications: 'Easier: Stay in shallower water, move slower, take frequent breaks, simplify arm movements. Harder: Move to deeper water, increase speed, add water dumbbells, do higher impact moves. Listen to your body above following class.',
  },
  {
    name: 'Group Exercise Class',
    description: 'Cardiac rehab or senior fitness class',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Class setting',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    instructions: '1. Join appropriate level class\n2. Inform instructor of cardiac history\n3. Modify exercises as needed\n4. Work at sustainable pace\n5. Enjoy social aspect',
    recoveryBenefit: 'Social support critical for long-term adherence, professional guidance, full-body workout, accountability and motivation',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 45,
    isActive: true,
    formTips: 'Inform instructor of cardiac surgery history and limitations. Position yourself near door for exit if needed. Monitor heart rate frequently. Take breaks whenever needed - ignore keeping up with class. Stay within your prescribed heart rate zone. Have water available.',
    modifications: 'Easier: Follow instructor\'s easier modifications, take more frequent breaks, reduce range of motion, slow down pace. Harder: Follow standard moves, add light weights if offered, reduce breaks, increase range. Choose appropriate class level - cardiac rehab or senior fitness best.',
  },
  {
    name: 'Light Jogging Intervals',
    description: 'Brief jogging periods mixed with walking',
    category: 'cardio',
    difficulty: 'advanced',
    equipmentNeeded: 'None',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    contraindications: 'Only with physician approval, sternum must be fully healed',
    instructions: '1. Warm up with 10 minutes walking\n2. Jog slowly for 1 minute\n3. Walk 4 minutes\n4. Repeat 4-5 times\n5. Cool down 5 minutes walking',
    recoveryBenefit: 'For patients cleared to advance to jogging, provides higher intensity cardio, builds cardiovascular capacity, increases exercise options',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 30,
    isActive: true,
    formTips: 'CRITICAL: Physician approval required. Excellent walking base needed first. Jog very slowly - barely faster than walking. Stay in prescribed heart rate zone. Land mid-foot, not heel. Keep shoulders relaxed. Stop immediately if chest discomfort, unusual breathlessness, or dizziness.',
    modifications: 'Easier: Jog 30 seconds only, walk 5 minutes between, total 20 minutes, jog on flat surface only. Harder: Increase jog to 2 minutes, reduce walk to 3 minutes, extend total time, add gentle hills. Never progress too quickly - this is advanced activity.',
  },
  {
    name: 'Full Squats',
    description: 'Complete squats to 90 degrees',
    category: 'lower_body',
    difficulty: 'advanced',
    equipmentNeeded: 'None',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    instructions: '1. Stand with feet shoulder-width apart\n2. Lower body by bending knees and hips\n3. Go down until thighs parallel to ground\n4. Keep chest up, weight in heels\n5. Push back up to standing',
    recoveryBenefit: 'Builds full leg strength for all activities, improves functional capacity, strengthens major muscle groups, boosts metabolism',
    defaultSets: 3,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Feet shoulder-width, toes slightly out. Descend by pushing hips back (like sitting in chair). Keep chest up and weight in heels. Knees track over toes, don\'t cave in. Squat to thighs parallel only. Drive through heels to stand. Core engaged throughout.',
    modifications: 'Easier: Squat to chair (touch and go), reduce depth to 45 degrees, reduce to 8 reps, hold support. Harder: Increase depth slightly past parallel, increase to 15 reps, slow tempo (3-2-3), add light weight held at chest. Master form before adding weight.',
  },
  {
    name: 'Deadlift (Light Weight)',
    description: 'Lifting weight from floor with proper form',
    category: 'lower_body',
    difficulty: 'advanced',
    equipmentNeeded: '10-20 lb weight or barbell',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    contraindications: 'Only with complete healing and professional guidance',
    instructions: '1. Stand with weight on floor in front\n2. Bend at hips and knees to grasp weight\n3. Keep back straight, core engaged\n4. Lift by straightening legs and hips\n5. Lower with control',
    recoveryBenefit: 'Functional movement for safe lifting, strengthens entire posterior chain (back, glutes, hamstrings), prevents back injury',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'CRITICAL: Professional instruction recommended. Keep weight close to body. Back flat, never rounded. Lift with legs, not back. Core braced throughout. Look forward, not up or down. Lower weight controlled. Stop if back pain. Start with very light weight (10 lbs max).',
    modifications: 'Easier: Use 5-10 lbs only, reduce to 6-8 reps, elevate weight on box (shorter range), use trap bar if available. Harder: Increase to 15-20 lbs, increase to 12 reps, full range from floor, slow tempo. Never sacrifice form for weight.',
  },
  {
    name: 'Push-Ups (Standard)',
    description: 'Full push-ups from floor',
    category: 'upper_body',
    difficulty: 'advanced',
    equipmentNeeded: 'None',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    contraindications: 'Complete sternum healing required',
    instructions: '1. Start in plank position, hands under shoulders\n2. Keep body straight from head to heels\n3. Lower chest toward floor\n4. Push back up to start\n5. Core engaged throughout',
    recoveryBenefit: 'Excellent indicator of upper body strength recovery, builds chest/shoulder/arm strength, functional pushing power',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'CRITICAL: Only after 11+ weeks and complete sternum healing. Body forms straight line head to heels. Hands under shoulders. Lower chest to 2-3 inches from floor. Elbows at 45 degrees. Core tight. Stop immediately if any sternum symptoms. Start conservatively.',
    modifications: 'Easier: Perform on knees, reduce range, reduce to 5-6 reps, incline hands on step. Harder: Full range to floor, increase to 15 reps, slow tempo, pause at bottom, elevate feet. This is an achievement milestone - don\'t rush it.',
  },
  {
    name: 'Pull-Ups (Assisted)',
    description: 'Pulling body up using assistance',
    category: 'upper_body',
    difficulty: 'advanced',
    equipmentNeeded: 'Assisted pull-up machine or resistance band',
    minPostOpWeek: 12,
    maxPostOpWeek: null,
    instructions: '1. Grasp bar with overhand grip\n2. Use assistance as needed\n3. Pull body up until chin over bar\n4. Lower with control\n5. Build up gradually',
    recoveryBenefit: 'Ultimate pulling strength exercise, builds back and arm strength, improves grip strength, shows full recovery',
    defaultSets: 2,
    defaultReps: 6,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Use assistance machine set appropriately. Grip bar firmly. Pull with back muscles, not just arms. Bring chin over bar. Lower with control. Core engaged. This is very advanced - most people need significant assistance initially. No shame in that.',
    modifications: 'Easier: Use maximum assistance, perform partial range, reduce to 3-4 reps, use band assistance. Harder: Reduce assistance gradually, increase range, increase to 8-10 reps, slow tempo. Can substitute lat pulldowns initially. This may take months to achieve.',
  },

  // CORE ADVANCED
  {
    name: 'Plank',
    description: 'Holding body straight in plank position',
    category: 'core',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 9,
    maxPostOpWeek: null,
    instructions: '1. Start on forearms and toes\n2. Keep body in straight line from head to heels\n3. Engage core and glutes\n4. Hold for 15-60 seconds\n5. Breathe normally',
    recoveryBenefit: 'Best core strengthening exercise, stabilizes spine, improves posture, builds endurance in core muscles',
    defaultSets: 3,
    defaultReps: 1,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Body forms straight line from head to heels. Elbows under shoulders. Core and glutes engaged. Look down, keep neck neutral. Don\'t hold breath - breathe normally. Stop if back sags or trembling becomes excessive. Quality over duration.',
    modifications: 'Easier: Perform on knees, hold 10-15 seconds only, incline on bench. Harder: Hold 45-60 seconds, lift one leg, lift one arm, perform on unstable surface. Build duration gradually - add 5 seconds per week.',
  },
  {
    name: 'Side Plank',
    description: 'Plank on side to target obliques',
    category: 'core',
    difficulty: 'advanced',
    equipmentNeeded: 'None',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    instructions: '1. Lie on side, forearm on ground\n2. Stack feet or stagger for easier\n3. Lift hips off ground\n4. Keep body straight from head to feet\n5. Hold 15-30 seconds each side',
    recoveryBenefit: 'Strengthens obliques and lateral core stability, improves balance, prevents side-to-side collapse, functional strength',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Stack feet or stagger for easier balance. Keep body straight - hips shouldn\'t sag. Bottom elbow directly under shoulder. Core and obliques engaged. Breathe normally. This is advanced - start with very short holds.',
    modifications: 'Easier: Keep bottom knee on ground, hold 10-15 seconds, perform against wall. Harder: Stack feet, hold 30-45 seconds, lift top leg, lift top arm, add hip dips. Progress gradually.',
  },
  {
    name: 'Mountain Climbers (Slow)',
    description: 'Alternating knee drives in plank',
    category: 'core',
    difficulty: 'advanced',
    equipmentNeeded: 'None',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    instructions: '1. Start in plank position\n2. Bring right knee toward chest\n3. Return to plank\n4. Bring left knee toward chest\n5. Alternate in controlled manner',
    recoveryBenefit: 'Dynamic core exercise with cardio component, builds core strength and endurance, improves coordination',
    defaultSets: 2,
    defaultReps: 20,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Start in solid plank position. Bring knee toward chest smoothly. Core engaged throughout. Hips stay level - don\'t pike up. Move with control, not speed. Breathe continuously. This is advanced exercise with cardio component.',
    modifications: 'Easier: Step feet in slowly (not driving), reduce to 10 reps, elevate hands on bench, keep hands on ground and slide feet. Harder: Increase speed slightly, increase to 30 reps, bring knee to opposite elbow, add push-up between reps. Never sacrifice form.',
  },

  // BALANCE ADVANCED
  {
    name: 'Single Leg Deadlift',
    description: 'Balancing on one leg while hinging forward',
    category: 'balance',
    difficulty: 'advanced',
    equipmentNeeded: 'None or light weight',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    instructions: '1. Stand on right leg\n2. Hinge forward at hip, extending left leg behind\n3. Reach toward floor with hands\n4. Keep back straight\n5. Return to standing\n6. Switch legs',
    recoveryBenefit: 'Advanced balance and strength combination, strengthens glutes and hamstrings, improves proprioception, functional movement',
    defaultSets: 2,
    defaultReps: 8,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Keep standing leg slightly bent. Hinge from hip, not waist. Reach toward floor while extending back leg. Keep back flat. Core engaged for balance. This is very challenging - use support initially. Stop if balance is poor or back pain.',
    modifications: 'Easier: Use support, don\'t lower far, touch down with back toe, reduce to 5-6 reps. Harder: No support, increase range, hold weight in hands, hold at bottom 2 seconds. Can perform on unstable surface when proficient.',
  },
  {
    name: 'Bosu Ball Squats',
    description: 'Squatting on unstable surface',
    category: 'balance',
    difficulty: 'advanced',
    equipmentNeeded: 'Bosu ball or balance disc',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    instructions: '1. Stand on Bosu ball (flat side down)\n2. Find balance\n3. Perform squat on unstable surface\n4. Use arms for balance\n5. Return to standing',
    recoveryBenefit: 'Challenges balance and stability systems, strengthens ankle and knee stabilizers, improves proprioception, reduces fall risk',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Step onto Bosu carefully. Find balance before squatting. Squat depth reduced due to instability. Keep core extra tight. Use arms for balance. Keep weight in heels. This is very advanced - master regular squats first.',
    modifications: 'Easier: Use support nearby, squat just few inches, reduce to 6-8 reps, use flatter side of Bosu up. Harder: No support, increase depth, increase to 15 reps, add light weight, close eyes briefly. Progress gradually.',
  },

  // FUNCTIONAL MOVEMENTS
  {
    name: 'Carrying Objects (Farmer\'s Walk)',
    description: 'Walking while carrying weights',
    category: 'upper_body',
    difficulty: 'advanced',
    equipmentNeeded: 'Dumbbells or weighted objects',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    instructions: '1. Hold moderate weight in each hand\n2. Stand upright with good posture\n3. Walk forward 20-30 steps\n4. Keep shoulders back and core engaged\n5. Turn and walk back',
    recoveryBenefit: 'Mimics carrying groceries and real-life activities, builds grip strength, improves core stability, functional strength',
    defaultSets: 3,
    defaultReps: 1,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Hold weights at sides with straight arms. Walk with good posture - chest up, shoulders back. Take normal stride. Core engaged. Walk in straight line. Start with light weight. Stop if grip failing or balance compromised.',
    modifications: 'Easier: Use 5-10 lbs per hand, walk just 20 feet, take breaks, walk slowly. Harder: Increase to 15-25 lbs, walk 50 feet+, increase pace, use one hand only (suitcase carry). This is highly functional exercise.',
  },
  {
    name: 'Reaching and Lifting Practice',
    description: 'Practicing overhead reaching with light object',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Light object (1-2 lbs)',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    instructions: '1. Start with object at waist level\n2. Lift object overhead reaching high\n3. Lower slowly to waist\n4. Place on low surface\n5. Lift back to waist\n6. Repeat sequence',
    recoveryBenefit: 'Practices functional movements needed for daily life (reaching shelves, putting things away), builds confidence in daily activities',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
    formTips: 'Start with very light object (1 lb). Reach overhead with control. Keep core engaged. Lower slowly. Squat down to pick up from floor - don\'t bend at waist. This practices daily activities. Stop if shoulder or back discomfort.',
    modifications: 'Easier: Use lighter object, don\'t reach as high, reduce reps, stay seated. Harder: Use 3-5 lb object, reach higher, add squatting component, increase reps. Practice functional patterns you need in daily life.',
  },
  {
    name: 'Stair Step Patterns',
    description: 'Various stepping patterns on stairs',
    category: 'cardio',
    difficulty: 'advanced',
    equipmentNeeded: 'Staircase',
    minPostOpWeek: 11,
    maxPostOpWeek: null,
    instructions: '1. Step up two steps at a time\n2. Step down one at a time\n3. Side step up stairs\n4. Use handrail for safety\n5. Vary patterns for challenge',
    recoveryBenefit: 'Advanced functional training for stairs, builds confidence in varied stair situations, improves leg strength and coordination',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 10,
    isActive: true,
    formTips: 'Always use handrail. Take time with each pattern. Step fully onto step. Lower slowly. Stop if you feel unsteady or fatigued. This is advanced - requires good fitness base. Never rush.',
    modifications: 'Easier: Single step pattern only, hold rail firmly, reduce reps, take longer breaks. Harder: Try two steps at a time, side steps, cross-over steps, reduce rail use. Build confidence gradually.',
  },
  {
    name: 'Agility Ladder Drills',
    description: 'Foot patterns through ladder on ground',
    category: 'cardio',
    difficulty: 'advanced',
    equipmentNeeded: 'Agility ladder or chalk marks',
    minPostOpWeek: 12,
    maxPostOpWeek: null,
    instructions: '1. Lay ladder flat on ground\n2. Step through squares with quick feet\n3. Try various patterns (one foot each, both feet, lateral)\n4. Start slow, increase speed gradually\n5. Focus on coordination',
    recoveryBenefit: 'Improves coordination and agility, challenges cardiovascular system, fun variation, builds confidence in quick movements',
    defaultSets: 3,
    defaultReps: 3,
    defaultDuration: 10,
    isActive: true,
    formTips: 'Start slowly - this isn\'t about speed initially. Watch foot placement. Stay light on feet. Keep core engaged. Breathe continuously. Stop if you feel unsteady. This improves coordination. Focus on pattern accuracy before speed.',
    modifications: 'Easier: Simple pattern (one foot each square), move slowly, reduce time, walk through pattern first. Harder: Complex patterns (both feet each, lateral, hop), increase speed, extend duration, add direction changes. Make it fun.',
  },
];

export async function seedExercises() {
  try {
    console.log('Seeding exercises...');

    const exerciseCount = await Exercise.count();
    if (exerciseCount > 0) {
      console.log(`Found ${exerciseCount} existing exercises. Clearing...`);
      await Exercise.destroy({ where: {} });
      console.log('Cleared all existing exercises.');
    }

    await Exercise.bulkCreate(exercises);
    console.log(`✅ Successfully seeded ${exercises.length} exercises`);
  } catch (error) {
    console.error('Error seeding exercises:', error);
    throw error;
  }
}

if (require.main === module) {
  seedExercises()
    .then(() => {
      console.log('Exercise seeding completed');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Exercise seeding failed:', error);
      process.exit(1);
    });
}
