import Exercise from '../models/Exercise';

type ExerciseCategory = 'upper_body' | 'lower_body' | 'cardio' | 'flexibility' | 'balance' | 'breathing' | 'core';
type ExerciseDifficulty = 'beginner' | 'intermediate' | 'advanced';

interface ExerciseSeedData {
  name: string;
  description: string;
  category: ExerciseCategory;
  difficulty: ExerciseDifficulty;
  equipmentNeeded: string;
  minPostOpWeek: number;
  maxPostOpWeek: number | null;
  contraindications?: string;
  instructions: string;
  defaultSets: number;
  defaultReps: number;
  defaultDuration: number;
  isActive: boolean;
}

const exercises: ExerciseSeedData[] = [
  // ========== BREATHING EXERCISES (Post-op Weeks 1-12) ==========
  {
    name: 'Deep Breathing Exercise',
    description: 'Slow, deep breaths to improve lung capacity and oxygen intake',
    category: 'breathing',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    contraindications: 'Severe chest pain, dizziness',
    instructions: '1. Sit comfortably with back straight\n2. Inhale slowly through nose for 4 counts\n3. Hold for 2 counts\n4. Exhale slowly through mouth for 6 counts\n5. Repeat 10 times',
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Incentive Spirometer Exercise',
    description: 'Breathing exercise using spirometer device to prevent lung complications',
    category: 'breathing',
    difficulty: 'beginner',
    equipmentNeeded: 'Incentive spirometer',
    minPostOpWeek: 1,
    maxPostOpWeek: 8,
    instructions: '1. Sit upright\n2. Exhale normally\n3. Place mouthpiece in mouth\n4. Inhale slowly and deeply\n5. Try to raise piston to target level\n6. Hold breath for 3-5 seconds\n7. Exhale slowly\n8. Rest briefly and repeat',
    defaultSets: 1,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Diaphragmatic Breathing',
    description: 'Belly breathing to strengthen diaphragm and improve breathing efficiency',
    category: 'breathing',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Lie on back or sit comfortably\n2. Place one hand on chest, one on belly\n3. Inhale through nose, expanding belly (not chest)\n4. Exhale slowly through pursed lips\n5. Feel belly fall while chest remains still',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },

  // ========== FLEXIBILITY & STRETCHING (Post-op Weeks 2-12) ==========
  {
    name: 'Neck Rotation Stretch',
    description: 'Gentle neck stretches to relieve tension',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 2,
    maxPostOpWeek: null,
    instructions: '1. Sit or stand with good posture\n2. Slowly turn head to look over right shoulder\n3. Hold for 10 seconds\n4. Return to center\n5. Repeat on left side',
    defaultSets: 2,
    defaultReps: 5,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Shoulder Rolls',
    description: 'Gentle shoulder mobility exercise',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 2,
    maxPostOpWeek: null,
    instructions: '1. Sit or stand with arms relaxed at sides\n2. Roll shoulders forward in circular motion\n3. Complete 5 circles\n4. Reverse direction for 5 circles backward',
    defaultSets: 2,
    defaultReps: 5,
    defaultDuration: 3,
    isActive: true,
  },
  {
    name: 'Ankle Circles',
    description: 'Ankle mobility exercise to prevent blood clots and improve circulation',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 1,
    maxPostOpWeek: null,
    instructions: '1. Sit in chair or lie down\n2. Lift one foot off ground\n3. Rotate ankle clockwise 10 times\n4. Rotate counterclockwise 10 times\n5. Repeat with other foot',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Seated Hamstring Stretch',
    description: 'Gentle hamstring stretch while seated',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair',
    minPostOpWeek: 3,
    maxPostOpWeek: null,
    instructions: '1. Sit on edge of chair\n2. Extend one leg straight with heel on floor\n3. Keep other foot flat on floor\n4. Lean forward gently from hips\n5. Hold for 15-30 seconds\n6. Repeat with other leg',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Calf Stretch',
    description: 'Standing calf stretch to improve lower leg flexibility',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'Wall or chair for support',
    minPostOpWeek: 3,
    maxPostOpWeek: null,
    instructions: '1. Stand facing wall, arms extended\n2. Step back with one leg, keeping it straight\n3. Bend front knee\n4. Keep both heels on floor\n5. Hold for 20-30 seconds\n6. Switch legs',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Quadriceps Stretch',
    description: 'Standing quad stretch for front thigh flexibility',
    category: 'flexibility',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair for balance',
    minPostOpWeek: 4,
    maxPostOpWeek: null,
    instructions: '1. Stand holding chair for balance\n2. Bend one knee, bringing foot toward buttocks\n3. Gently pull foot closer with hand\n4. Keep knees together\n5. Hold for 20 seconds\n6. Switch legs',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },

  // ========== UPPER BODY EXERCISES (Post-op Weeks 6-12) ==========
  {
    name: 'Arm Raises (Front)',
    description: 'Gentle shoulder strengthening with forward arm raises',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Light dumbbells (1-2 lbs) or none',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    contraindications: 'Recent sternal surgery (check with surgeon)',
    instructions: '1. Stand with feet shoulder-width apart\n2. Hold light weights or no weight\n3. Raise arms forward to shoulder height\n4. Hold for 2 seconds\n5. Lower slowly\n6. Keep elbows slightly bent',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Arm Raises (Side)',
    description: 'Lateral shoulder strengthening exercise',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Light dumbbells (1-2 lbs) or none',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Stand with arms at sides\n2. Raise arms out to sides to shoulder height\n3. Keep palms facing down\n4. Hold briefly\n5. Lower slowly',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Bicep Curls',
    description: 'Arm strengthening focusing on biceps',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Light dumbbells (2-5 lbs)',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Stand with weights in hands, palms facing forward\n2. Keep elbows close to body\n3. Curl weights toward shoulders\n4. Squeeze biceps at top\n5. Lower slowly',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Overhead Press (Light)',
    description: 'Shoulder press with light weights',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Light dumbbells (2-3 lbs)',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    contraindications: 'Recent sternal surgery without clearance',
    instructions: '1. Sit or stand with weights at shoulder height\n2. Press weights overhead\n3. Fully extend arms without locking elbows\n4. Lower slowly to shoulder height',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Wall Push-Ups',
    description: 'Modified push-ups against wall for upper body strength',
    category: 'upper_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Wall',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    contraindications: 'Unstable sternum, severe shoulder pain',
    instructions: '1. Stand arm\'s length from wall\n2. Place hands on wall at shoulder height\n3. Lean forward, bending elbows\n4. Push back to starting position\n5. Keep body straight throughout',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },

  // ========== LOWER BODY EXERCISES (Post-op Weeks 3-12) ==========
  {
    name: 'Seated Marching',
    description: 'Gentle leg exercise while seated',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Sturdy chair',
    minPostOpWeek: 2,
    maxPostOpWeek: null,
    instructions: '1. Sit upright in chair\n2. Lift one knee toward chest\n3. Lower foot back to floor\n4. Repeat with other leg\n5. Alternate legs in marching motion',
    defaultSets: 2,
    defaultReps: 20,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Heel Raises (Calf Raises)',
    description: 'Strengthens calf muscles and improves circulation',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair or wall for balance',
    minPostOpWeek: 3,
    maxPostOpWeek: null,
    instructions: '1. Stand with feet hip-width apart\n2. Hold chair for balance\n3. Rise up on toes\n4. Hold for 2 seconds\n5. Lower heels to floor',
    defaultSets: 2,
    defaultReps: 15,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Sit-to-Stand',
    description: 'Functional exercise for leg strength and daily activities',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Sturdy chair',
    minPostOpWeek: 3,
    maxPostOpWeek: null,
    instructions: '1. Sit in chair with feet flat on floor\n2. Lean forward slightly\n3. Stand up without using hands if possible\n4. Stand fully upright\n5. Slowly sit back down',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Leg Extensions (Seated)',
    description: 'Quadriceps strengthening while seated',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair',
    minPostOpWeek: 3,
    maxPostOpWeek: null,
    instructions: '1. Sit in chair with back supported\n2. Extend one leg straight out\n3. Hold for 3-5 seconds\n4. Lower slowly\n5. Repeat with other leg',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Standing Knee Lifts',
    description: 'Hip flexor and quad strengthening',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair for balance',
    minPostOpWeek: 4,
    maxPostOpWeek: null,
    instructions: '1. Stand holding chair for balance\n2. Lift one knee toward chest\n3. Keep standing leg slightly bent\n4. Hold for 2-3 seconds\n5. Lower and repeat\n6. Switch legs',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Mini Squats',
    description: 'Partial squats for leg strengthening',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Chair for support (optional)',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    contraindications: 'Severe knee pain, balance issues',
    instructions: '1. Stand with feet shoulder-width apart\n2. Lower body by bending knees slightly (45 degrees)\n3. Keep weight on heels\n4. Don\'t let knees go past toes\n5. Return to standing\n6. Use chair for balance if needed',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Side Leg Raises',
    description: 'Hip abductor strengthening',
    category: 'lower_body',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair for balance',
    minPostOpWeek: 4,
    maxPostOpWeek: null,
    instructions: '1. Stand holding chair with one hand\n2. Lift outer leg out to side\n3. Keep leg straight\n4. Hold for 2 seconds\n5. Lower slowly\n6. Switch sides',
    defaultSets: 2,
    defaultReps: 12,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Step-Ups',
    description: 'Functional leg strengthening using step',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Low step or sturdy platform (4-6 inches)',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Stand facing step\n2. Place one foot on step\n3. Push through heel to step up\n4. Bring other foot up\n5. Step down with same foot\n6. Alternate leading foot',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Forward Lunges (Modified)',
    description: 'Controlled lunge for leg strengthening',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Stand with feet together\n2. Step forward with one foot\n3. Lower back knee toward floor (don\'t touch)\n4. Keep front knee over ankle\n5. Push back to starting position\n6. Alternate legs',
    defaultSets: 2,
    defaultReps: 8,
    defaultDuration: 5,
    isActive: true,
  },

  // ========== CARDIO EXERCISES (Post-op Weeks 2-12) ==========
  {
    name: 'Walking (Indoor)',
    description: 'Level walking at comfortable pace indoors',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 2,
    maxPostOpWeek: null,
    instructions: '1. Walk at comfortable pace\n2. Maintain good posture\n3. Swing arms naturally\n4. Start with 5-10 minutes\n5. Gradually increase duration\n6. Monitor heart rate',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 10,
    isActive: true,
  },
  {
    name: 'Walking (Outdoor)',
    description: 'Outdoor walking on level surface',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'Comfortable walking shoes',
    minPostOpWeek: 3,
    maxPostOpWeek: null,
    instructions: '1. Choose flat, safe route\n2. Walk at comfortable pace\n3. Be aware of weather conditions\n4. Start with 10-15 minutes\n5. Gradually increase\n6. Monitor how you feel',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 15,
    isActive: true,
  },
  {
    name: 'Treadmill Walking',
    description: 'Controlled walking on treadmill',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'Treadmill',
    minPostOpWeek: 4,
    maxPostOpWeek: null,
    instructions: '1. Start at slow speed (1.5-2.0 mph)\n2. Hold handrails if needed for balance\n3. Maintain upright posture\n4. Gradually increase speed and duration\n5. Monitor heart rate\n6. Cool down with slower pace',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 15,
    isActive: true,
  },
  {
    name: 'Stationary Bike (Recumbent)',
    description: 'Low-impact cycling on recumbent bike',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'Recumbent stationary bike',
    minPostOpWeek: 4,
    maxPostOpWeek: null,
    instructions: '1. Adjust seat so knees are slightly bent at full extension\n2. Start with no resistance\n3. Pedal at comfortable pace\n4. Gradually increase resistance\n5. Monitor heart rate\n6. Start with 5-10 minutes',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 10,
    isActive: true,
  },
  {
    name: 'Stationary Bike (Upright)',
    description: 'Standard stationary bike exercise',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Upright stationary bike',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Adjust seat height properly\n2. Start with light resistance\n3. Maintain steady pace\n4. Keep shoulders relaxed\n5. Gradually increase resistance and duration',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 20,
    isActive: true,
  },
  {
    name: 'Elliptical Machine',
    description: 'Low-impact cardio on elliptical',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Elliptical machine',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Start with no incline\n2. Use light resistance\n3. Maintain upright posture\n4. Move smoothly without bouncing\n5. Use arm handles for full body workout\n6. Start with 10 minutes',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 15,
    isActive: true,
  },
  {
    name: 'Swimming (Gentle)',
    description: 'Low-impact swimming or water walking',
    category: 'cardio',
    difficulty: 'intermediate',
    equipmentNeeded: 'Pool access',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    contraindications: 'Open wounds, recent surgery',
    instructions: '1. Ensure surgical incisions are fully healed\n2. Start with water walking\n3. Progress to gentle swimming\n4. Avoid breast stroke initially\n5. Start with 10-15 minutes\n6. Water should be comfortable temperature',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 15,
    isActive: true,
  },
  {
    name: 'Marching in Place',
    description: 'Simple cardio exercise that can be done anywhere',
    category: 'cardio',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 3,
    maxPostOpWeek: null,
    instructions: '1. Stand with feet hip-width apart\n2. Lift knees alternately as if marching\n3. Swing arms naturally\n4. March at comfortable pace\n5. Start with 2-3 minutes\n6. Gradually increase duration',
    defaultSets: 3,
    defaultReps: 1,
    defaultDuration: 3,
    isActive: true,
  },

  // ========== BALANCE EXERCISES (Post-op Weeks 4-12) ==========
  {
    name: 'Single-Leg Stand',
    description: 'Basic balance exercise standing on one leg',
    category: 'balance',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair or wall for support',
    minPostOpWeek: 4,
    maxPostOpWeek: null,
    instructions: '1. Stand near wall or chair\n2. Lift one foot slightly off ground\n3. Balance on standing leg\n4. Hold for 10-30 seconds\n5. Switch legs\n6. Use support as needed',
    defaultSets: 3,
    defaultReps: 1,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Heel-to-Toe Walk',
    description: 'Walking in straight line for balance',
    category: 'balance',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 5,
    maxPostOpWeek: null,
    instructions: '1. Position heel of one foot just in front of toes of other foot\n2. Walk in straight line\n3. Each step, touch heel to toe\n4. Focus eyes forward, not down\n5. Walk 10-15 steps',
    defaultSets: 2,
    defaultReps: 1,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Standing on One Leg (Eyes Closed)',
    description: 'Advanced balance challenge',
    category: 'balance',
    difficulty: 'intermediate',
    equipmentNeeded: 'Clear space, nearby support',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Master this with eyes open first\n2. Stand near support\n3. Lift one foot\n4. Close eyes\n5. Balance for 10-20 seconds\n6. Open eyes before putting foot down',
    defaultSets: 3,
    defaultReps: 1,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Clock Reach',
    description: 'Dynamic balance exercise reaching in different directions',
    category: 'balance',
    difficulty: 'intermediate',
    equipmentNeeded: 'None',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Stand on one leg\n2. Imagine standing in center of clock\n3. Reach with free leg to "12 o\'clock" (forward)\n4. Return to center\n5. Reach to "3 o\'clock" (side)\n6. Reach to "6 o\'clock" (back)\n7. Switch legs',
    defaultSets: 2,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },

  // ========== CORE EXERCISES (Post-op Weeks 6-12) ==========
  {
    name: 'Seated Core Twist',
    description: 'Gentle torso rotation for obliques',
    category: 'core',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Sit upright in chair\n2. Place hands behind head\n3. Gently twist torso to right\n4. Return to center\n5. Twist to left\n6. Move slowly and controlled',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Abdominal Bracing',
    description: 'Isometric core strengthening',
    category: 'core',
    difficulty: 'beginner',
    equipmentNeeded: 'None',
    minPostOpWeek: 4,
    maxPostOpWeek: null,
    instructions: '1. Sit or stand with good posture\n2. Tighten abdominal muscles as if bracing for a punch\n3. Breathe normally while holding\n4. Hold for 10 seconds\n5. Release and repeat',
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Pelvic Tilts (Seated)',
    description: 'Gentle lower back and core exercise',
    category: 'core',
    difficulty: 'beginner',
    equipmentNeeded: 'Chair',
    minPostOpWeek: 4,
    maxPostOpWeek: null,
    instructions: '1. Sit upright in chair\n2. Tilt pelvis forward, arching lower back slightly\n3. Then tilt pelvis backward, flattening lower back\n4. Move slowly between positions\n5. Feel muscles working in lower back and abs',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Modified Plank (Wall)',
    description: 'Core strengthening using wall support',
    category: 'core',
    difficulty: 'intermediate',
    equipmentNeeded: 'Wall',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    contraindications: 'Unstable sternum, severe upper body weakness',
    instructions: '1. Stand arm\'s length from wall\n2. Place hands on wall at shoulder height\n3. Step feet back\n4. Keep body straight from head to heels\n5. Hold plank position\n6. Start with 10-15 seconds',
    defaultSets: 3,
    defaultReps: 1,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Bird Dog (Modified)',
    description: 'Core stability exercise on hands and knees',
    category: 'core',
    difficulty: 'intermediate',
    equipmentNeeded: 'Exercise mat',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    contraindications: 'Recent sternal surgery without clearance',
    instructions: '1. Start on hands and knees\n2. Keep back flat, core engaged\n3. Extend one arm forward\n4. Hold for 5 seconds\n5. Return to start\n6. Repeat with other arm\n7. Progress to extending opposite leg',
    defaultSets: 2,
    defaultReps: 8,
    defaultDuration: 5,
    isActive: true,
  },

  // ========== ADDITIONAL FUNCTIONAL EXERCISES ==========
  {
    name: 'Carrying Groceries Simulation',
    description: 'Functional exercise practicing daily activity',
    category: 'upper_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Light weights or grocery bags (2-5 lbs)',
    minPostOpWeek: 8,
    maxPostOpWeek: null,
    instructions: '1. Hold light weights in each hand\n2. Walk slowly across room\n3. Maintain good posture\n4. Keep shoulders back\n5. Start with 2-3 lbs per hand\n6. Walk for 1-2 minutes',
    defaultSets: 2,
    defaultReps: 1,
    defaultDuration: 2,
    isActive: true,
  },
  {
    name: 'Stair Climbing (Single Step)',
    description: 'Practice stepping up and down single step',
    category: 'lower_body',
    difficulty: 'intermediate',
    equipmentNeeded: 'Single step with handrail',
    minPostOpWeek: 6,
    maxPostOpWeek: null,
    instructions: '1. Stand at bottom of step\n2. Hold handrail\n3. Step up with stronger leg\n4. Bring other leg up\n5. Step down with weaker leg first\n6. Repeat slowly',
    defaultSets: 2,
    defaultReps: 10,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Stair Climbing (Full Flight)',
    description: 'Climbing full flight of stairs',
    category: 'cardio',
    difficulty: 'advanced',
    equipmentNeeded: 'Stairs with handrail',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    instructions: '1. Hold handrail for safety\n2. Climb at comfortable pace\n3. Rest at top if needed\n4. Descend slowly and carefully\n5. Monitor heart rate\n6. Start with one flight',
    defaultSets: 1,
    defaultReps: 1,
    defaultDuration: 5,
    isActive: true,
  },
  {
    name: 'Getting Up from Floor',
    description: 'Functional exercise for fall recovery',
    category: 'lower_body',
    difficulty: 'advanced',
    equipmentNeeded: 'Exercise mat, nearby chair',
    minPostOpWeek: 10,
    maxPostOpWeek: null,
    instructions: '1. Sit on floor near chair\n2. Roll to hands and knees\n3. Use chair for support\n4. Bring one foot forward\n5. Push up to standing\n6. Practice with supervision first',
    defaultSets: 1,
    defaultReps: 3,
    defaultDuration: 5,
    isActive: true,
  },
];

export async function seedExercises() {
  try {
    console.log('🌱 Starting Exercises seeding...');

    // Clear existing exercises
    await Exercise.destroy({ where: {} });
    console.log('✅ Cleared existing exercises');

    // Create exercises
    const createdExercises = await Exercise.bulkCreate(exercises);
    console.log(`✅ Created ${createdExercises.length} exercises`);

    // Log summary by category
    const categories = exercises.reduce((acc, exercise) => {
      acc[exercise.category] = (acc[exercise.category] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    // Log summary by difficulty
    const difficulties = exercises.reduce((acc, exercise) => {
      acc[exercise.difficulty] = (acc[exercise.difficulty] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    console.log('\n📊 Exercises Summary:');
    console.log('By Category:');
    Object.entries(categories).forEach(([category, count]) => {
      console.log(`   ${category}: ${count} exercises`);
    });
    console.log('\nBy Difficulty:');
    Object.entries(difficulties).forEach(([difficulty, count]) => {
      console.log(`   ${difficulty}: ${count} exercises`);
    });

    return createdExercises;
  } catch (error) {
    console.error('❌ Error seeding exercises:', error);
    throw error;
  }
}

// Run if called directly
if (require.main === module) {
  const sequelize = require('../models/database').default;

  sequelize.sync()
    .then(() => seedExercises())
    .then(() => {
      console.log('\n✅ Exercises seeding completed successfully!');
      process.exit(0);
    })
    .catch((error: Error) => {
      console.error('\n❌ Seeding failed:', error);
      process.exit(1);
    });
}
