apiVersion: v1
kind: Service
metadata:
  name: {{ include "heartbeat-calendar.fullname" . }}-backend
  labels:
    app: {{ include "heartbeat-calendar.name" . }}
    component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "heartbeat-calendar.name" . }}
    component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "heartbeat-calendar.fullname" . }}-frontend
  labels:
    app: {{ include "heartbeat-calendar.name" . }}
    component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "heartbeat-calendar.name" . }}
    component: frontend