apiVersion: v2
name: heartbeat-calendar
description: HeartBeat Calendar Monorepo - Backend, UI, DB
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "12.1.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled