replicaCount: 1

image:
  backend:
    repository: johndesautels1/heartbeat-backend
    tag: "latest"
    pullPolicy: IfNotPresent
  frontend:
    repository: johndesautels1/heartbeat-frontend
    tag: "latest"
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  backend:
    port: 8080
  frontend:
    port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: heartbeat.example.com
      paths:
        - path: /api
          pathType: Prefix
          service: backend
        - path: /
          pathType: Prefix
          service: frontend
  tls:
    - secretName: heartbeat-tls
      hosts:
        - heartbeat.example.com

postgresql:
  enabled: true
  auth:
    username: heartbeat
    password: changeme
    database: heartbeat_calendar
  primary:
    persistence:
      enabled: true
      size: 10Gi

env:
  NODE_ENV: production
  DB_HOST: heartbeat-calendar-postgresql
  DB_PORT: 5432
  DB_NAME: heartbeat_calendar
  DB_USER: heartbeat
  DB_PASS: changeme
  JWT_SECRET: your-secret-jwt-key

secrets:
  googleOAuth:
    clientId: ""
    clientSecret: ""
  apple:
    clientId: ""
    teamId: ""
    keyId: ""
    privateKey: ""
  twilio:
    accountSid: ""
    authToken: ""
    phoneNumber: ""
  firebase:
    projectId: ""
    clientEmail: ""
    privateKey: ""
  smtp:
    host: smtp.gmail.com
    port: 587
    user: ""
    pass: ""

resources:
  backend:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  frontend:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}